### ISSUE TITLE
Can not manage Google Chrome

### ISSUE THREAD

**Issue by zarudama** [fuhsjr00/bug.n#1]
Hi. I use "bug.n" always.
I love this tool.
I was not able to manage Chrome from yesterday.

Windows Google Chrome Version

``` sh
34.0.1847.116 m 
```
# i::Manager_getWindowInfo()

``` sh
ID: 0xd041a
class:  Chrome_WidgetWin_1
title:  New Issue · fuhsjr00/bug.n - Google Chrome
process:    chrome.exe
style:  0x17CF0000
metrics:    x: -4, y: 8, width: 1608, height: 1168
tags:   
```

Thank your for reply.

**Comment by cognivore** [comment]
I'm just curious if this issue reappeared for someone else on bug.n version `9.1.0` with Google Chrome version `83.0.4103.97`?

**Comment by cognivore** [comment]
In `Config.ahk` rules 12-14 are present:

```
Config_rule_#12  := "Chrome_WidgetWin_1;.*;;1;0;0;0;1;0;"
Config_rule_#13  := "Chrome_WidgetWin_1;.*;Window_isPopup;0;0;0;1;1;0;"
Config_rule_#14  := "Chrome_RenderWidgetHostHWND;.*;;0;0;0;1;1;0;"
```
