### ISSUE TITLE
Warning popped up

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#101]
If ever you can make sth out of it:

![capture](https://cloud.githubusercontent.com/assets/1562517/15184438/76476b2e-1795-11e6-8530-e135215386b5.PNG)

Got only this once, when calling`View_setLayoutProperty(Axis, 0, +1, 1)`. I saw no negative consequence afterwards.

**Comment by joten** [comment]
Please test with 744ee1f7d709c263667673e0a1e92d155c539547, when convenient.

**Comment by joten** [comment]
Further warnings are circumvented.

It may be possible those issues cannot easily be fixed with `_isFloating` set to `False = 0 = ""` being garbage collected and therewith not assigned a value afterwards.
