### ISSUE TITLE
Another warn window

### ISSUE THREAD

**Issue by arturocastro** [fuhsjr00/bug.n#102]
Popped out when logging off from Win7 64 bit, current bug.n development version.
Not sure if this is normal behavior or not.

![image](https://cloud.githubusercontent.com/assets/6549359/15220938/f513037a-182e-11e6-9c21-5392f5a5a4e6.png)

Happened again when clicking on a tag in monitor 3, but I'm still unsure how to reproduce it.

Now, it also happened as soon as I ran bug.n. Same message.

**Comment by arturocastro** [comment]
Happened again when clicking on a tag in monitor #3, but I'm still unsure how to reproduce it.

**Comment by joten** [comment]
I tried to fix this issue with commit d2998c9cbce2e012aa67a1a26cbf47d2b03a61a1. Please give it a spin.

On the other hand it would be interesting to see your `_WindowState.ini` regarding this issue; there seems to be a `View_#m_#v_wndIds` with an empty value. Can you provide it?

**Comment by arturocastro** [comment]
I applied the fix, I'll use it around a couple of days to see if the warning pops out again.

How can I provide my `_WindowState.ini`?

**Comment by arturocastro** [comment]
I got a similar popup with the fix applied:

![image](https://cloud.githubusercontent.com/assets/6549359/15338278/dd8ad1a0-1c44-11e6-8ce3-6e79a53a68c6.png)

So far, it's only happened once.

**Comment by joten** [comment]
I will fix the specific issue with my next commit and circumvent any further warnings of this kind.

The `_WindowState.ini` can be found in `%APPDATA%\bug.n\data\` as the `log.txt` can be found in `%APPDATA%\bug.n\`, i. e. `C:\Users\%USERNAME%\AppData\Roaming\bug.n\`.
