### ISSUE TITLE
Error on bugn.exe execute

### ISSUE THREAD

**Issue by arturocastro** [fuhsjr00/bug.n#103]
![image](https://cloud.githubusercontent.com/assets/6549359/15222311/abd17f4c-1834-11e6-93f9-239e70b2b289.png)
Win7 64 bit, latest development version of bug.n. Running Main.ahk works.

Current release (9 beta 1) works fine.

**Comment by joten** [comment]
Sorry, I cannot reproduce the problem on Windows 10; I do not have Windows 7 at hand.

Perhaps you could try the following:
* Check the file permissions.
* Copy bugn.exe to the src-directory and run it there.
* If not already done, run bugn.exe without a `Config.ini`.

**Comment by arturocastro** [comment]
Moving `bugn.exe` to `src/` worked, I'm not sure what's going on...

**Comment by x29a** [comment]
Can you please check with [ProcMon](https://technet.microsoft.com/en-us/library/bb896645.aspx) which resource it is trying to access? Maybe its related to the icon? Have you tried running without Config.ini?
