### ISSUE TITLE
Rule for Cygwin/X windows

### ISSUE THREAD

**Issue by arturocastro** [fuhsjr00/bug.n#105]
I see that there is a rule in Config.ahk for xming, so that windows aren't handled like popus and are managed by bug.n as regular windows (so these windows are tiled).

I don't use xming, however, I use the X Server that comes with Cygwin.

I haven't been able to properly set up a rule for these windows.

Here's windows spy on xterm:

![image](https://cloud.githubusercontent.com/assets/6549359/15558362/20589156-229f-11e6-907f-850774c20dac.png)

Here's the original rule for xming (first line is the comment on rule syntax): 

    ;; Config_rule_#<i> := "<class>;<title>;<function name>;<is managed>;<m>;<tags>;<is floating>;<is decorated>;<hide title>;<action>"
    Config_rule_#6   := "Xming;.*;;1;0;0;0;0;0;"

The rules I've tried (but don't seem to work) are:

    Config_rule_#18   := "cygwin/x X rl;.*;;1;0;0;0;0;0;"
    Config_rule_#18   := "cygwin/x X rl;zsh;;1;0;0;0;0;0;"
    Config_rule_#18   := "cygwin/x;.*;;1;0;0;0;0;0;"
    Config_rule_#18   := "X;.*;;1;0;0;0;0;0;"

I've tried them one by one. I've set up `Config_ruleCount := 18` as well. I test by running Main.ahk directly.

Has anyone successfully set this up?

**Comment by joten** [comment]
I cannot reproduce this, I am not using cygwin. But perhaps the following will work: 

Config.ahk: `Config_rule_#18   := "cygwin.x.*;.*;;1;0;0;0;0;0;"`

Config.ini: `Config_rule=cygwin.x.*;.*;;1;0;0;0;0;0;`

`<class>` and `<title>` use [regular expressions](https://autohotkey.com/docs/misc/RegEx-QuickRef.htm).

**Comment by joten** [comment]
Did the proposed cygwin rule work?

**Comment by dc46and2** [comment]
Worked for me. Thanks joten!
