### ISSUE TITLE
Bug.n AHK script unpauses itself

### ISSUE THREAD

**Issue by janus0** [fuhsjr00/bug.n#107]
I'm using a separate script to toggle AHK scripts on/off. The issue is the bug.n ahk script seems to unpause itself and resize windows such as notepad when I open them up (it also still removes the minimize/maximize/close buttons in the top right as if it weren't suspended+paused). I see the ahk script icon in the notification area switch from red with an 's' to green with an 's'. The script I'm using to pause+suspend all other scripts is below (not my script).
```
WM_COMMAND := 0x111
CMD_RELOAD := 65400
CMD_EDIT := 65401
CMD_PAUSE := 65403
CMD_SUSPEND := 65404

DetectHiddenWindows, On

Process, Exist
this_pid := ErrorLevel
control_id := WinExist("ahk_class AutoHotkey ahk_pid " this_pid)

; Press Home to toggle Pause & Suspend state for all scripts.
capslock::
WinGet, id, list, ahk_class AutoHotkey
Loop, %id%
{
	this_id := id%A_Index%
    If (this_id <> control_id)
	{
		PostMessage, WM_COMMAND, CMD_PAUSE,,, ahk_id %this_id%
		PostMessage, WM_COMMAND, CMD_SUSPEND,,, ahk_id %this_id%
	}
}
return
```

**Comment by joten** [comment]
Additional to the keyboard and mouse hook from AutoHotkey, bug.n uses a shell hook; this is not suspended, if you suspend the AutoHotkey script.

You may set `Config_dynamicTiling` to `False` (no function or hotkey supplied by bug.n) or the layout to `><>` (<kbd>Win</kbd><kbd>F</kbd>), but windows would still be managed and rules applied, i. e. by default the decor.
