### ISSUE TITLE
Config_hotkey only accepts single commands

### ISSUE THREAD

**Issue by ddurschlag** [fuhsjr00/bug.n#109]
Not a huge expert on bug.n or AHK, so this may be an issue on my end. I couldn't find an IRC channel or other project communication mechanism, however.

I'd like to have a single key combo switch all my monitors to the same view. It seems like this means using Manager_activateMonitor repeatedly to switch monitors, then Monitor_activateView on each one. I've tried and failed to find a way to do this using Config_hotkey in config.ini.

Is there a right way to do this? If so, what is it? If not, could one be added?

**Comment by huffstler** [comment]
I haven't really delved into all the different possibilities of customizing hotkeys with bug.n, so this may or may not work / be supported.

You might be able to write a small script that does that for you, and then run that script when a certain hotkey is used.

**Comment by joten** [comment]
From [bug.n/doc/Default_configuration.md](https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_configuration.md):

`Config_syncMonitorViews=0`

> The number of monitors (2 or more), for which views should be activated, when
using the accordant hotkey. If set to 1, the views are activated for all
monitors. If set to 0, views are activated independently (only on the active
monitor).

In your case you may add the following line to your Config.ini:

`Config_syncMonitorViews=1`

This will determine bug.n's general behaviour for `Monitor_activateView`; you will not be able to switch views independently, if this variable is set.
