### ISSUE TITLE
Is it possible to name tags?

### ISSUE THREAD

**Issue by kiru** [fuhsjr00/bug.n#113]
I'd like to name each tags instead of 1 to 9 with actual name, like: "browser" "IDE" "chat" 

I'm not sure if that is possible, couldn't find any clue in the documentation.

**Comment by joten** [comment]
From the section "Window arrangement" in [bug.n/doc/Default_configuration.md](https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_configuration.md):

`Config_viewNames=1;2;3;4;5;6;7;8;9`
> The names of the views separated by a semicolon. This variable sets the names
of the views shown in the status bar and determines the number of views
(`Config_viewCount`); the total number of names given, i. e. views, should not
be exceeded by the configured hotkeys.

In your case you may add the following line to your Config.ini:
`Config_viewNames=browser;IDE;chat`

**Comment by kiru** [comment]
@joten thank you. Is it possible to set different names on different monitors?

**Comment by joten** [comment]
No, currently, this is not supported; it would be possible to implement, but would also conflict with `Config_syncMonitorViews`.

**Comment by kiru** [comment]
@joten Thanks, for now views with names are sufficient for me.
