### ISSUE TITLE
Custom display for status bar?

### ISSUE THREAD

**Issue by lurdan** [fuhsjr00/bug.n#114]
hi,

Is it difficult to add something like "readinCustom" to display file content somewhere or command output?

I have too large space for displaying window title, so I want to put some information other than
default resource monitors.

**Comment by joten** [comment]
You would have to run bug.n as a script with AutoHotkey ([bug.n/doc/Installing_and_running.md](https://github.com/fuhsjr00/bug.n/blob/master/doc/Installing_and_running.md)) and adjust the function `Config_readinAny()` in 'Config.ahk' more precisely the returned variable `text` to your needs.
