### ISSUE TITLE
win+<left>  win+<right> not working

### ISSUE THREAD

**Issue by cmal** [fuhsjr00/bug.n#115]
I just start to use this bug.n and find some problem:
The first time I open bugn.exe, it works well and I read all about the cheatsheet and know the controlling of it. Everything works well and I have a nice day.
The next day I restarted my win7, and found that the win+<left> and win+<right> does not working.
Further, I can not even know which window is the master window, because every window on desktop just occupy the same size, and distributed evenly on the screen.
Finally, whenever I opens a new tab in chrome, (chrome is one of the windows on screen) the windows on screen will become smaller to make a vacate for a new window. But actually there isn't a new window. So part of the screen will be blank and shows the desktop background. But after I input the url in the new chrome tab(it redirects to the target page), the windows will resize to fill the screen.
I've tested these problems in 8.4.0 stable and master. Both has the same problem.
Can you help me with this problem? Thanks and thank you for your excellent work.

**Comment by cmal** [comment]
There is another thing: The schedule task (start windows with bugn.exe) does not work, either.

**Comment by joten** [comment]
> The next day I restarted my win7...

Could you restart bug.n without restoring the session and solve the problem? Or could you reproduce the problem at all?

There is not really a "master window", only a master area in the 'tile' layout, which is by default on the left or top, unless you used `#^t::View_setLayoutProperty("Axis", 0, +1, 1)`.

Regarding Chrome: Do you have an active rule like `Config_rule=Chrome_WidgetWin_1;.*;;1;0;2;0;0;0;maximize` as mentioned in issue #79? Or may `Config_rule=Chrome_RenderWidgetHostHWND;.*;;0;0;0;0;1;0;` as mentioned in issue #22 solve your problem?

Regarding 'task schedule': Did you configure the task as described in the documentation (https://github.com/fuhsjr00/bug.n/blob/master/doc/Installing_and_running.md#create-a-task-in-task-scheduler)?

**Comment by cmal** [comment]
Thanks. Restoring the session does solve the problem.
As for the other two problems, I will keep an eye on them and see what happens.
I didn't find a `Chrome` thing in the config file and the task schedule, yes, I've configured the task exactly as described.
Maybe later I'll find the answer and then I'll post it on this page. Thank you!

**Comment by aedahl** [comment]
@cmal Were your issues resolved?  If so, I think we can close this issue.

**Comment by cmal** [comment]
closed. Sorry for that, I lost my windows laptop, only use mac now.
