### ISSUE TITLE
Confused By Task Bar Heading of 2x1|=

### ISSUE THREAD

**Issue by tompurl** [fuhsjr00/bug.n#117]
I noticed today that I wasn't able to resize my windows in one of my virtual terminals using keyboard commands. I tried changing to and from the tiled layout and restarting, but my second virtual terminal still has this in the task bar:

    2x1|=

The rest of my virtual terminals have this:

    1x1|=

...and those behave as expected. 

Do you know how I can change this back to the `1x1|=` setting? Here's the non-rules part of my `Config.ini`:

    Monitor_#1_aView_#2=2
    View_#1_#1_layoutGapWidth=2
    View_#1_#1_layoutMFact=0.650000
    View_#1_#2_layoutMFact=0.500000
    View_#1_#3_layoutMFact=0.400000
    View_#1_#9_layoutMFact=0.250000
    Monitor_#2_aView_#1=2
    View_#2_#1_layoutGapWidth=6
    View_#2_#3_layoutMFact=0.550000
    View_#2_#9_layoutMFact=0.500000

**Comment by yehya** [comment]
Ctrl + CMD + Left Arrow

**Comment by yehya** [comment]
That's the 2 equal columns grid setting, so you can only resize when there's 3 or more Windows open on that VD. However you will be resizing 2 main Windows instead of 1 main window.

**Comment by tompurl** [comment]
Oh that is so freaking cool! I didn't know you could change how the windows were arranged by changing the x and y dimension. 

For anyone Googling this later, please see the Default_hotkeys.md doc and look for the "Increase the master Y dimension" section as a start.

Thanks a bunch! Is this feature documented anywhere else? Is there a good place where I can add this documentation?
