### ISSUE TITLE
Move one window to second monitor

### ISSUE THREAD

**Issue by trigun539** [fuhsjr00/bug.n#120]
Can't find documentation on how to move a window to another monitor. The only command I see is using "win + ctrl + alt + ." to move all windows to second monitor. Haven't been able to move a single window to second monitor.

**Comment by yehya** [comment]
For default it's "WIN + SHIFT + ." to move to right window, and ""WIN + SHIFT + ," to move to left window.

**Comment by trigun539** [comment]
Awesome, thank you!
