### ISSUE TITLE
Free !Up and !Down

### ISSUE THREAD

**Issue by Lexanius** [fuhsjr00/bug.n#125]
Hiho,

it is possible to free/remap the binding !Up and !Down that i can use it in Editors again. It often use to move a line one top/bottom. Editors are Eclipse or VSC. With bug.n the keybinding not work correctly, nothing happends.
How can I configure the app that it works normal? Maybe other keybindings?

Greetings, 

Lexanius

**Comment by x29a** [comment]
Hi,

Which version of Windows are you on?

According to the [default hotkey documentation](https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_hotkeys.md#window-management) that combo is only active with dynamic tiling is disabled, do you have dynamic tiling disabled in your config? 

To disable the default mapping, you should be able to provide the combo without a function name, as described in the [customization docu](https://github.com/fuhsjr00/bug.n/blob/master/doc/Customization.md#customizing-bugn) so try

> Config_hotkey=!Up::
> Config_hotkey=!Down::

in your _Config.ini_ (see [configuration docu](https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_configuration.md)).

**Comment by Lexanius** [comment]
This work. Thx

To the questions: I use the v8.4.0 and i have dynamic tiling on and use the exe to start the application.
