### ISSUE TITLE
Moving active window 1 tag to the left/right doesn't work.

### ISSUE THREAD

**Issue by siffiejoe** [fuhsjr00/bug.n#137]
I'm trying to move the currently active window to the next (or previous) tag using

    Monitor_setWindowTag(0, +1)

This has no effect.

Changing

      If (i = 0)
        i := Monitor_#%Manager_aMonitor%_aView_#1
      Else If (i <= Config_viewCount)
        i := Manager_loop(i, d, 1, Config_viewCount)

in `Monitor_setWindowTag` to

      If (i = 0)
        i := Monitor_#%Manager_aMonitor%_aView_#1
      If (i <= Config_viewCount)
        i := Manager_loop(i, d, 1, Config_viewCount)

seems to fix the issue. (It might not be the cleanest workaround, but it works.)

**Comment by joten** [comment]
You are right. The workaround did it, although, in the end I changed the line to `If Not (i = 10)`; there was a possible additional bug regarding false user input (e.g. `Monitor_setWindowTag(11)`).
