### ISSUE TITLE
Use GitHub releases for .exe distribution

### ISSUE THREAD

**Issue by vktec** [fuhsjr00/bug.n#145]
Version controlling an EXE results in pretty huge diffs every time you recompile. Git wasn't designed to handle binary files efficiently, so I'd suggest uploading the EXE to the relevant GitHub release instead.

**Comment by alphaCTzo7G** [comment]
isnt git lfs designed for large files? I can now upload >100 mb files to github using git lfs. However there are some bugs in there.

**Comment by vktec** [comment]
Git LFS would improve the diff issue, but Git isn't really designed for distribution. GitHub releases are specifically designed for releasing software, and have file upload so you can upload binaries.

The point is less about the technology (though that's certainly part of it) and more about the workflow: Git is for **source** version control. It's not for releasing software or distributing binaries.

**Comment by alphaCTzo7G** [comment]
You are right. I didnt know about GitHub releases, as I use git and git lfs all personal projects. As bug.n gets more mature, and widely used, it might be worthwhile to invest and start using github releases.

**Comment by joten** [comment]
Is it more of an academical or a practical problem? The size of the executable is about 300kB, as is the cheat sheet PDF, and there are some PNG files, which are around 100kB.

But even if it is more of an academical problem, I do undestand your point. Personally, I am a bit lazy with the releases, and it is convenient for debugging to have an executable in the development version, which reflects the current code. This way you can download the development version as a ZIP file, and it more or less contains the same files as a release.

With GitHub releases you mean https://github.com/fuhsjr00/bug.n/releases?
If I do undestand you correctly, not only the executable, but the PDF and PNG files should also be moved to the release, which then would reflect the state of the source files at the time of the release.

**Comment by joten** [comment]
I removed most binary files from the main repository, either they were moved to the Wiki (usr/* with its image files) or will be created by the build script (bugn.exe and cheat sheet files) when making a release.
On second thought I found it appealing not recreating the bugn.exe with every change I make to the source --, which would be only consequent regarding the purpose of the exe in the ZIP download of the repository as a quasi development release.
