### ISSUE TITLE
"Overlay" windows not floating properly

### ISSUE THREAD

**Issue by NickSeagull** [fuhsjr00/bug.n#146]
Two examples that I've found in my system:

When opening snipping tool in rectangular mode I cannot click anywhere on the white overlay that it generates to crop a region on the screen:

![image](https://user-images.githubusercontent.com/7448243/31638479-cc03d00c-b2cb-11e7-9900-7dbf5baaf4bd.png)

The Snipping Tool stays tiled on top and the overlay is unclickable.

Another example is when using a program called [Hunt and Peck](https://github.com/zsims/hunt-and-peck), which generates an overlay over all clickable items on the screen showing some keystrokes to click on them:

![hap](https://camo.githubusercontent.com/387d7b14dcc93e27b13edfcbd6d6be2fe3db24e2/68747470733a2f2f7261772e6769746875622e636f6d2f7a73696d732f68756e742d6e2d7065636b2f6d61737465722f73637265656e73686f74732f6578706c6f7265722e706e67)

If I spawn it myself, the overlay gets tiled and doesnt render correctly:

![image](https://user-images.githubusercontent.com/7448243/31638554-2980e3c8-b2cc-11e7-9217-3343014c6882.png)

My exclude rule for Hunt and Peck is the following (I've tracked the class using `WinGetClass` and it always includes the word `hap`):

```ahk
Config_rule_#19   := "*hap*;.*hap*;*hap*;0;0;1;1;1;1;"
```

In case that I'm doing something wrong, the actual class name is `HwndWrapper[hap.exe;;<random hexadecimal number each time>]`

Thanks for bug.n, it is really awesome.
Also thanks for taking the time to read this 😄

**Comment by joten** [comment]
I could not reproduce the issue running Windows 10 and the current bug.n code (no Config.ini) with AutoHotkey 1.1.27.00 (32-bit); although the content of the Snipping Tool window was a bit distorted.

You may use the following rule to make the according windows floating:
`Config_rule=Microsoft-Windows-Snipper.*;Snipping Tool;;1;0;0;1;1;0;`

**Comment by NickSeagull** [comment]
Tested this in a new system, works correctly, thanks!!

Closing

**Comment by lluke777** [comment]
Hi NickSeagull
How the final rule for HAP looks like?
Thanks

**Comment by tantoinet** [comment]
One more rule fixing Captura:
;;captura
Config_rule=;Region Picker;;0;1;;0;0;0;

Raw output from #i:
ID: 0x100b70
class:	HwndWrapper[captura.exe;;b8efdf34-657b-40ab-8320-46ba0a226e76]
title:	Region Picker
process:	captura.exe [5200]
style:	0x16080000
metrics:	x: 0, y: 0, width: 1920, height: 1080
tags:	--

Config_rule=HwndWrapper[captura.exe;;b8efdf34-657b-40ab-8320-46ba0a226e76];Region Picker;;0;;;;;0;
