### ISSUE TITLE
Unable to turn on title bar for notepad++

### ISSUE THREAD

**Issue by Asteryz** [fuhsjr00/bug.n#152]
I don't want bug.n to change the way my windows look yet. I tried changing the general rules but that didn't work so I wanted to try the more specific case of fixing notepad++ and then generalizing. But I can't get notepad++ to play ball.

I'm using bug.n-9.0.0-beta.1 and have the following in my Config.ini, which starts off with the result of a getWindowInfo query for notepad++.

```
;ID: 0x60a4a
;class:	Notepad++
;title:	*C:\Users\USERNAME\AppData\Roaming\bug.n\Config.ini - Notepad++
;process:	notepad++.exe [13956]
;style:	0x160F0000
;metrics:	x: 2298, y: 12, width: 1547, height: 336
;tags:	1
;
;Config_rule=Notepad++;*C:\Users\USERNAME\AppData\Roaming\bug.n\Config.ini - Notepad++;;1;1;1;0;0;0;

; The config rule I came up with: (Changed the title and flipped the isDecorated flag)
Config_rule=Notepad++;.*;;1;1;1;0;1;0;
```

Is something not working as intended? Or am I being stupid and missing something?

Thanks,
Marc

**Comment by joten** [comment]
You may try one of the following Config.ini-lines:

`Config_rule=Notepad\+\+;.* - Notepad\+\+;;1;0;0;0;1;0;` or

`Config_rule=Notepad..;.*Notepad..;;1;0;0;0;1;0;`

The first to fields of the rule are regular expressions as described in the [AutoHotkey documentation](https://www.autohotkey.com/docs/misc/RegEx-QuickRef.htm).

**Comment by Asteryz** [comment]
Thank you, I tried the second config rule and it seems to work as intended.
