### ISSUE TITLE
Cursor resets to center of screen when changing desktops

### ISSUE THREAD

**Issue by joelgraff** [fuhsjr00/bug.n#158]
It's not a big deal, but it's a bit annoying when changing desktops, that the mouse cursor is reset to the center of the screen.  I would consider that behavior that most users would not expect to have happen.  It's really only a problem, though, when I'm switching through desktops, looking for a particular window I had forgotten where I put it.

**Comment by groenmj** [comment]
Putting the following line in your config.ini will stop this behaviour:

`Config_mouseFollowsFocus=0`

**Comment by joelgraff** [comment]
Works great.  Thanks!
