### ISSUE TITLE
Hide titles in bar

### ISSUE THREAD

**Issue by mkrnr** [fuhsjr00/bug.n#159]
Would it be possible to add a config option to remove the title from the bar?

Sadly, it is not an option for me to remove the window titles in Windows 10 since most programs that I use look quite ugly with a removed window title. Thereby, I would have this redundant information (title in the window itself and in the bar).

**Comment by joten** [comment]
One possibility would be to set the corresponding option (hide title) in the default rule:
`Config_rule_#1=.*;.*;;1;0;0;0;0;1;`
Additionally, you should set the option in any rule, which sets the option "is decorated", e.g.:
`Config_rule_#10=CabinetWClass;.*;;1;0;0;0;1;1;`

(The title field in the bar is the one field, which is stretched to the remaining space of the bar.)

**Comment by mkrnr** [comment]
Thank you @joten! That works perfectly. Especially the fact that the title field is streched to the remaining space made it possible for me to completely hide it by shrinking the width of the bar.
