### ISSUE TITLE
Incompatible with Display Scaling

### ISSUE THREAD

**Issue by morinted** [fuhsjr00/bug.n#16]
## Description

When running bug.n in an environment with display scaling on, it doesn't handle it well, and most of the bar is off screen.

## Snapshot

![The problem in question](https://cloud.githubusercontent.com/assets/5840970/5339636/02cd5ea2-7eb1-11e4-8622-461ab1849be0.png)

## Platform

Windows 8.1, 64 bit

## Steps to reproduce

1. Enable display scaling in Windows. There are two kinds

    a. Enabling the "size" of elements option, from smaller to larger

    b. Enabling the "Let me choose one scaling size for all monitors" option, and setting that to a percentage greater than 100%.

2. Start bug.n

**Comment by joten** [comment]
It seems to work. 

Issue #18 could not be reproduced.
