### ISSUE TITLE
Why some applications don't tile like ex. Neovim (qt), VLC? They got also title bar visible just above window.

### ISSUE THREAD

**Issue by lluke777** [fuhsjr00/bug.n#160]

**Comment by joten** [comment]
VLC is qritten with Qt, too, I think, and there is `Config_rule_#4=QWidget;.*;;1;0;0;0;0;0;`, which relates to the corresponding windows. Did you change `Config_rule_#4` or replaced it?

**Comment by lluke777** [comment]
I got the same line. I didn't change anything at rules.
`Config_rule_#4=QWidget;.*;;1;0;0;0;0;0;` 
How it should look like to prevent that problem?

**Comment by joten** [comment]
Which version of VLC are aou using? Perhaps they moved to Qt5, in which case you would need a something like `Config_rule=Qt5QWindowIcon;.*;;1;0;0;0;0;0;`.

You may use the hotkey <kbd>Win</kbd><kbd>i</kbd> for showing the window information of the currently active window. Please post the line starting with `Config_rule` from the results here.
