### ISSUE TITLE
hotkey to activate view to left or right

### ISSUE THREAD

**Issue by shaunsmiley-rms** [fuhsjr00/bug.n#168]
In awesome wm, there are keyboard shortcuts META+Left and META+Left go to the to the left or right of the currently active view.  I can't find a way to do this.  Of course simply using META+<number> works, but I'd like to add this in addition to my config.

**Comment by joten** [comment]
Have a look at [the 'View/ Tag management' section in doc/Default_hotkeys](https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_hotkeys.md#view--tag-management): There are no predefined hotkeys, but you may add the following two lines to your Config.ini, which should produce this functionality:
```
!Left::Monitor_activateView(0, -1)
!Right::Monitor_activateView(0, +1)
```
Depending on what your "META" key is --: In th default configuration <kbd>Win</kbd><kbd>Left</kbd> and <kbd>Win</kbd><kbd>Right</kbd> are used for adjusting size of the master area, but <kbd>Alt</kbd><kbd>Left</kbd> and <kbd>Alt</kbd><kbd>Right</kbd> are currently not used.

**Comment by shaunsmiley-rms** [comment]
Brilliant!  This works perfectly.  Thanks!
