### ISSUE TITLE
Some rules ignored

### ISSUE THREAD

**Issue by sfranky** [fuhsjr00/bug.n#177]
Hi guys! lovely tool, thanks for making this!

what does it mean when a rule is not obeyed? could there be something wrong in my .ini file?
e.g. I fire up Emacs, which has a secondary cmdprompt window show up. I'm doing #i to see the rule, I get
`Config_rule=ConsoleWindowClass;C:\Program Files\emacs\bin\emacs.exe;;1;1;128;1;0;0;`
I then copy this in my .ini file and change e.g. the tag to 2, or float status, save and reload.
Nothing changes. If I do #i, I get the same.
Any ideas?
thanks!

**Comment by joten** [comment]
By default `Config_autoSaveSession=auto`, which restores the previous window settings, if the window id is still found. You may try `Config_autoSaveSession=ask` in Config.ini or start a new instance of the Emacs window, if not already done.

Regarding the rule: The first two fields are interpreted as regular expressions; you may try `Config_rule=ConsoleWindowClass;.*emacs.exe;;1;1;2;1;0;0;`.

**Comment by sfranky** [comment]
thanks very much for your reply. I'm not sure I understood what you said, but I think it mostly works if I close and reopen the window, so thanks.
When is the session saved? What does it mean when it asks me if I want to restore an old session?
The regex solution worked, but I don't understand why the full name one would not, since it's the program itself that is giving me the suggestion for the name. Am I missing something?

**Comment by sfranky** [comment]
ok many thanks, everything clearer now! thanks again for all your work, this program is a godsend !!
