### ISSUE TITLE
Can't access minimized windows

### ISSUE THREAD

**Issue by harrdb12** [fuhsjr00/bug.n#184]
Not sure if this is intentional or not... after a window has been minimized, I can't seem to figure out how to access it again using bug.n; i.e. the normal hotkeys of Win+Up or Win+Down don't work. I find I have to either click on the minimized window or Alt+Tab to it. Is this behavior intentional?

**Comment by joten** [comment]
Minimizing a window, especially with `#^m::Manager_minimizeWindow()`, results in a floating window regarding bug.n. It was implemented for better compatibility to other window management requirements. In the context of bug.n minimizing a window does not make much sense -- that is, what views are for.

<kbd>Win</kbd><kbd>Up/Down</kbd> is an alternative to <kbd>Alt</kbd><kbd>Tab</kbd>, which only cycles through tiled (not floating) windows. Therefor <kbd>Alt</kbd><kbd>Tab</kbd> is the way to access a minimized window.

**Comment by harrdb12** [comment]
This makes sense; thank you for answering.
