### ISSUE TITLE
Flickering focus change since 20141031_bug.n-dev

### ISSUE THREAD

**Issue by x29a** [fuhsjr00/bug.n#19]
Hi,

i am using Bug.N in a dual-monitor (24", both run FullHD resolution via DVI) setup on a Windows 7 SP1 64bit, local user is running as administrator, i am running the application "run as administrator" as well. I provide a path to the application and i have write access there.

Since 20141031_bug.n-dev Bug.N is not usable anymore since windows seem to constantly change the focus, it is flickering and i cannot select any windows. Stopping Bug.N via the taskbar icon works (fortunately).

20141213_bug.n-dev shows the same behaviour, i am currently working with 20140930_bug.n-dev.

How can i provide more useful infos? Since i cant seem to attach the files directly, i uploaded my log.txt (http://pastebin.com/raw.php?i=MBe1v5q3) and my Config.ini (http://pastebin.com/raw.php?i=t6Kwrcrp).

Other programs that i am using that might interfere are launchy (http://www.launchy.net/) and InputDirector (http://www.inputdirector.com/), though Bug.N seems to struggle the most with IBM Lotus Notes.

Thanks for such a great piece of software, using i3wm on linux, Bug.N makes windows somewhat comfortable :)

**Comment by joten** [comment]
Uh, the problem for me is, that I do not have a test environment with Windows 7 and a dual-monitor setup. @fuhsjr00 Can you help?

My last tests with Windows 8.1 and a dual-monitor setup (which I do not use regularly) did not indicate any problems.

@x29a In the meantime, could you test the following?
* Running the current `bug.n-dev.exe` without Administrator privileges, no additional parameters and no `Config.ini` at all.
* Running the current `bug.n-dev.exe` without running _launchy_ or _InputDirector_ at the same time.

In both cases run _bug.n_, open some _Explorer_ windows and do some multi-monitor-window-action, i. a. move windows between monitors, activate different monitors, activate different views, close windows.

Thanks in advance.

**Comment by x29a** [comment]
Well, this is a bit embarrasing, in order to track the issue further down, i did as you said and disabled the "run as administrator" setting. I shut off input director and launchy, cleaned out the userdata\roaming\bug.n folder and started the 20141213_bug.n-dev.exe.
 
Everything works like a charm, but of course it is using my default config. So i copied my Config.ini to the appdata folder, restart. 

Still works. Moving windows between the monitors, all windows get the focus and use the maximum screen size. To make things short, i re-enabled the admin flag, i passed a path to the executable, i started launchy and input director and it still works. 

So it seems, i cannot reproduce this issue, so sorry for bugging you. 

I will stick with the default appdata path and the latest dev version now.

For future feedback:
- is there a more verbose debug level to enable?
- does the version in the Config.ini have any impact on the application behaviour?

**Comment by joten** [comment]
I am glad it works.

> is there a more verbose debug level to enable?

Currently, you cannot set a default debug log level, but you can increment the debug log level by using the hotkey `#^+d`, which calls `Debug_setLogLevel(+1)`.

> does the version in the Config.ini have any impact on the application behaviour?

No, it is just identifying the original version of `Config.ini` for user support.

> _WindowState.ini which was 118KB big. When i deleted that file

I guess, the file is gone, not in trash?

**Comment by x29a** [comment]
Nope, i just renamed the data folder. I cleaned out personal information from the file and uploaded it to http://pastebin.com/raw.php?i=0vWaUNjC
