### ISSUE TITLE
possible to force an app to always float

### ISSUE THREAD

**Issue by jimpriest** [fuhsjr00/bug.n#203]
I use two apps - an app launcher and a clipboard utility that both pop up in a window on a key press. 

Right now it pops up and then bug.n seems to grab it and maximize. 

Can I tell bug.n to leave these apps alone or always float them?

**Comment by jimpriest** [comment]
Of course I post and then I think I found it.

I can click WIN+I on the windows and it pops up 

Config_rule=TMainForm;Find and Run Robot 2 | Friday March 08, 2019  -  3:37 PM;;0;;;;;0;

Which I see examples of in the config.

**Comment by joten** [comment]
You are almost there; interestingly the above example should work, but bug.n uses [regular expressions](https://www.autohotkey.com/docs/misc/RegEx-QuickRef.htm) in [Config_rule](https://github.com/fuhsjr00/bug.n/blob/master/doc/Configuring_rules.md), whereas the pipe schould be escaped and for a more general rule I would suggest the following:
`Config_rule=TMainForm;Find and Run Robot.*;;0;;;;;0;` (therewith showing it an all views) or 
`Config_rule=TMainForm;Find and Run Robot.*;;0;0;0;1;1;0;`, if you want the window to be floating, with decoration, but only shown on the one view it was opened.

**Comment by jimpriest** [comment]
Thanks! I found the docs section that pertains to this  and am RTFM
https://github.com/fuhsjr00/bug.n/blob/master/doc/Configuring_rules.md
