### ISSUE TITLE
Running a function by default

### ISSUE THREAD

**Issue by ducklin5** [fuhsjr00/bug.n#209]
Is it possible to have the View_toggleMargins() function run when bug.n starts up?

**Comment by joten** [comment]
That is you have set `Config_viewMargins` to something different than `0;0;0;0`, but do not want the margins to be visible at start?

Currently the only way to do this, would be to edit the script and [run bug.n as a script with AutoHotkey](https://github.com/fuhsjr00/bug.n/blob/master/doc/Installing_and_running.md#installing-and-running-bugn). It should be sufficient to put `View_toggleMargins()` on line 56 in Main.ahk.

**Comment by ducklin5** [comment]
To clarify, I meant that I have set `Config_viewMargins= 10;200;5;5` but I **do want** the margins visible from the start. It seems that bug.n always starts off with the margins disabled. Using `Main.ahk` did resolve that issue though.

**Comment by joten** [comment]
`Config_viewMargins` are meant to be toggled quickly having a glimpse on part of the desktop. Permanent margins for e.g. additional bars are currently only recognized for Windows Taskbar and bblean.
