### ISSUE TITLE
chocolatey package

### ISSUE THREAD

**Issue by hnspn** [fuhsjr00/bug.n#213]
We should make a chocolatey package for easy installation.

[It](https://www.topbug.net/blog/2012/07/02/a-simple-tutorial-create-and-publish-chocolatey-packages/) doesn't look complicated.

**Comment by ertwro** [comment]
I made a manifest for scoop: [bugn.json](https://gist.github.com/ertwro/6ecab39267990e5dacd18a4ac287ddd2.js) that maybe could go into the extras bucket of scoop. I would like to add ```#Include CustomFuction.ahk``` in ```main.ahk```  to have persistent send and run functions after update. I'll take a look at making it for chocolatey but scoop is just so much more interesting.

**Comment by hnspn** [comment]
Had never heard of scoop before today.
Seems like an older and better package manager than chocolatey.
I wonder why it never took off.

Anyway, scoop extras just merged your json.
We should add the scoop installation instructions to the readme.

**Comment by ertwro** [comment]
@hnspn I've created a pull request adding it to the readme with instructions. Also, a couple of modifications to allow for more portability when updating. particularly scoop allows persistent configuration files from the source code so we could include a file to keep custom Run and Send functions for hotkeys.
