### ISSUE TITLE
Focus lost after closing Adobe Acrobat

### ISSUE THREAD

**Issue by blokeley** [fuhsjr00/bug.n#219]
For most programs, using <kbd>Win</kbd> <kbd>C</kbd> closes the current window, and focus returns to the "previous" window (I think the one next down the stack).

However, when I close Adobe Acrobat using <kbd>Win</kbd> <kbd>C</kbd>, no window is then in focus and I have to use <kbd>Alt</kbd> <kbd>Tab</kbd> to select one.

Weird.

Versions:
* bug.n 9.0.2
* Windows 10 Pro version 1809 build 17763.557
* Adobe Acrobat 2019.012.20035

**Comment by joten** [comment]
As far as I can see after looking through the code, bug.n is triggered by a shell message when the window is closed and wants to activate the last known active window on the current monitor/ view. Most likely Adobe Acrobat opens additional hidden windows, which get registered but cannot be activated afterwards.

**Comment by blokeley** [comment]
I think that Adobe Acrobat does not behave normally when it comes to window management (or much else like trying to run itself in the background all the time).

Another example is that opening a PDF from a file manager causes Adobe Acrobat to change the `bug.n` view to wherever the last Acrobat window was, and open the PDF in a new tab in that window.  It is the only program I have found which causes `bug.n` to switch views.

I'll close this issue because I doubt that there is anything that `bug.n` can do about it.

**Comment by joten** [comment]
In the current version of bug.n does not provide enough debugging information to see, what Adobe Acrobat does; therefor there is not much, which can be done to remedy this issue.

Regarding the opening of a new file you may set the Config.ini line `Config_onActiveHiddenWnds=tag`, with which bug.n would not change the view, but would add the Adobe Acrobat window to the current view.
