### ISSUE TITLE
Bug.n glitches with external monitor

### ISSUE THREAD

**Issue by ay2718** [fuhsjr00/bug.n#221]
Windows don't tile correctly in the external monitor, and the desktop icons will flash rapidly over an open window on the primary monitor if no window is selected.  Sometimes bug.n will just freeze.
I'm using version 9.0.2, with a stock config.

**Comment by joten** [comment]
That's odd and a weird behaviour.
* Which Windows version are you using?
* Can you attach a screenshot, not of "desktop icons will flash rapidly", but perhaps of "Windows don't tile correctly"?
* Do the desktop icons flash, if using a single monitor?
* Please also post the lines from the log beginning with "DEBUG[0] Monitor_init: #".

Perhaps, any of this yields a clue.

**Comment by ay2718** [comment]
Sorry for the late response.
The problem seems to come from monitor scaling.
On a single monitor, if the monitor scaling is changed (without logging out/in again), the windows will tile incorrectly.  My multimonitor setup is working fine with both monitors running at native resolution.

**Comment by ay2718** [comment]
This seems like a symptom of #155
