### ISSUE TITLE
How to retile a window?

### ISSUE THREAD

**Issue by dylanpjx** [fuhsjr00/bug.n#223]
1. Tile mode is set with #t
2. Maximise the current master window
3. Slave windows are currently still in tile mode, while master window is maximised in the foreground

At this stage, with a maximised master window, how do I retile my master window, is there a hotkey to shift it back to its original tile view. The minimise hotkey minimises the master window to the taskbar and reopening said window remaximises it.

**Comment by dylanpjx** [comment]
[Proposed label]: Question

**Comment by joten** [comment]
Re-tiling with <kbd>Win</kbd><kbd>T</kbd> should resize the maximized window to the master area, if you maximized the window via the title bar icon or Windows' hotkeys. 

If you maximized the window with <kbd>Win</kbd><kbd>Shift</kbd><kbd>X</kbd>, it would have been made floating, too. <kbd>Win</kbd><kbd>Shift</kbd><kbd>F</kbd> toggles the floating state of the window and the view should be re-arranged accordingly.
