### ISSUE TITLE
Reload bug.n from the command line

### ISSUE THREAD

**Issue by ertwro** [fuhsjr00/bug.n#228]
I use ```autohotkey.exe /r C:\[RepoDirectory]\src\Main.ahk```
When I try to run a command-line argument to reload Main.ahk, is not possible for the following reasons.
- It opens a new instance, despite adding ```#SingleInstance force``` at the top of Main.ahk
- Main.ahk tries to include the rest of the AHK files from the current directory in the shell and not from the src, directory in the bug.n folder.

I use vim as my text editor and would like to reload bug.every time I save the config.ini file. For that reason, I require a command-line way of reloading, or passing <kbd>Win</kbd><kbd>Ctrl</kbd><kbd>r</kbd> from the command line without another script, just to pass three simple keys.

At the moment I'm using a command-line application called *nircmd* and doing ```nricmdc.exe sendkeypress lwin+Ctrl+Shift+r``` which works but seems excessive to me.

**Comment by joten** [comment]
You may create a link e.g. C:\[RepoDirectory]\run_bugn.lnk for executing `"C:\Program Files\AutoHotkey\AutoHotkey.exe" C:\[RepoDirectory]\src\Main.ahk` with `C:\[RepoDirectory]\src` as the working directory. At least from cmd you can then run the link.

**Comment by ertwro** [comment]
I didn't know you could do that with windows links. Thanks.
