### ISSUE TITLE
readinCpu on secondary monitor

### ISSUE THREAD

**Issue by twnsnd** [fuhsjr00/bug.n#23]
When using bug.n with a multi monitor setup my secondary monitor permanently displays 'CPU:   0%'  for readinCpu on the bug.n bar. This is happening on windows 7 where all of the other readin displays work correctly.

**Comment by joten** [comment]
This should be fixed with 9bc942afa9b952f49ffec150c2217c953ce35970. I tested it today, and it looked good.
