### ISSUE TITLE
Chrome Blocks Download

### ISSUE THREAD

**Issue by turnipjs** [fuhsjr00/bug.n#231]
When you try to download the release (9.0.2) Chrome blocks the download. "bug.n-9.0.2.zip is dangerous, so Chrome has blocked it."
More info: https://support.google.com/chrome/answer/6261569?visit_id=637082627603671177-2127721456&p=ib_download_blocked&hl=en&rd=1

**Comment by x29a** [comment]
Thanks for reporting this, this is already being discussed in #212 and unfortunately, it seems like there is nothing one can do. You can run the scripts directly via AutoHotKey instead of using the compiled .exe.
