### ISSUE TITLE
Message that download files contain virus

### ISSUE THREAD

**Issue by hirschferkel** [fuhsjr00/bug.n#233]
Downloading the zip or tar files will cause an alert, that the download contains a virus?

**Comment by tantoinet** [comment]
bug.n is based on AutoHotkeys, which establises hooks. The AV engines are detecting those through generic signatures.
What I can suggest is that you send that sample file to your AV company asking them to whitelist it, as this is a False Positive.
If you are too lazy, just add an exclusion to the folder containing bugn.exe in your AV engine, and it should be fine.
Finally, you can read the scripts code to confirm that it's clean and of course, you can recompile it on your own.

**Comment by hirschferkel** [comment]
Just wanted to inform you about this issue. Thanks for your quick reply.

Best, hirschferkel
