### ISSUE TITLE
autohotkey.com vs ahkscript.org

### ISSUE THREAD

**Issue by MCTaylor17** [fuhsjr00/bug.n#236]
The link in README.md points to ahkscript.org/download/ which leads to the following:

![image](https://user-images.githubusercontent.com/7216377/71569685-b42bae80-2a85-11ea-9e44-7854f4d2c33b.png)

According to [this Reddit thread](https://www.reddit.com/r/AutoHotkey/comments/a756y4/autohotkey_vs_ahkscript) the domain has changed to autohotkey.com.

**Comment by joten** [comment]
Thanks for the hint; I hope I found all instances.
