### ISSUE TITLE
Elevated windows yield bad side effects

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#24]
A window that is run as administrator prevents to change view, as if it could not be left for a normal window.

A fix consisting of not managing elevated windows would be ok for me. For processes that I always run as elevated (as ProcessExplorer) I can add a rule for that. However, for those that I can run both ways (such as a debugging environment or a console), the rules do not enable to tell the elevated case apart.

My current workaround is to reload a modified config.ini that stops managing the windows that I want elevated. When all are closed, I resume my usual config.ini.

This is for version 8.3.1, as version 8.4 does anyway work badly for me with respect to focusing and view-changing behaviours.

**Comment by joten** [comment]
> A fix consisting of not managing elevated windows would be ok for me.

Done. It would be a very complex task to identify the elevated state of a window correctly. _bug.n_ now tries to change the title of the window, which does not work, if it is in an elevated state; for not-elevated windows the effect should not be visible.

> This is for version 8.3.1, as version 8.4 does anyway work badly for me with respect to focusing and view-changing behaviours.

The new code is, of course, in the development version i. e. 9.0.0, which is likely to have the same problems as version 8.4.0. Are you using multiple monitors (regarding the bad focusing and view-changing behaviour)?

**Comment by joten** [comment]
By the way, I run bug.n itself with administrative privileges, to be able to manage "elevated windows". That way the problem is circumvented.

**Comment by Chadehoc** [comment]
> By the way, I run bug.n itself with administrative privileges, to be able
> to manage "elevated windows". That way the problem is circumvented.

Excellent idea, I should have thought of that, thanks.

> The new code is, of course, in the development version i. e. 9.0.0, which
> is likely to have the same problems as version 8.4.0. Are you using multiple
> monitors (regarding the bad focusing and view-changing behaviour)?

Yes, two monitors. I had added a note on issue #21 because my problem is that bug.n often gets stuck in a state where changing view, or even focus, becomes impossible. This issue was about outlook, but my case seems more random. I was waiting for 9.0.0 to become stable before investigating more and trying to find patterns. If I can find something I will open a new issue.
