### ISSUE TITLE
Bug.n Reload with custom configuration directory

### ISSUE THREAD

**Issue by Solace7** [fuhsjr00/bug.n#240]
Greetings,

I've got bugn setup via Task Scheduler pointing to a custom directory instead of the default %appdata% directory. When I run the reload command it uses a default configuration file instead of the Config.ini that I have. Is there a way to have the reload command point to the specific directory?

**Comment by joten** [comment]
No, currently not. There had been a function, which reloaded only the configuration, but it has been removed. You need to re-run bug.n via Task Scheduler.
