### ISSUE TITLE
Windows key bindings aren't being overridden

### ISSUE THREAD

**Issue by marnunez** [fuhsjr00/bug.n#244]
Hi! Running bug.n 0.9.2, from compiled exe, adm privileges.
I'm finding that the default Win+key are not overridden, resulting in:

- Win+E still opens Explorer
- Every #+key binding also opens the Screen Magnifier (triggered by the Win+ combination)
- Win+D still shows the desktop

etc

Tried it also with the development version, same results. Anyone experiencing this problem as well?

**Comment by joten** [comment]
This is intentional. The default key bindings, which provide helpful functionality not replaced by bug.n functions, should still be accessible as far as possible; e.g. only #+d, #^d and #+^d are used by bug.n, but not #d.

**Comment by marnunez** [comment]
Ok, understood. But regarding the #+(any key) binding, that will pop up the Screen Magnifier regardless of the key I press. Is that normal as well? There seem to be many bug.n defaults that include the #+(key) binding, such as #+I

**Comment by joten** [comment]
Ah, well, `#+` is a symbolic notation used by AutoHotkey representing <kbd>Win</kbd><kbd>Shift</kbd>. Have a look at the cheat sheet from the release file for an overview of the default hockeys.

**Comment by marnunez** [comment]
:man_facepalming:  I use AutoHotkey nearly every day... can't believe this got pass me haha. Thanks!
