### ISSUE TITLE
Config file not working properly

### ISSUE THREAD

**Issue by javesar** [fuhsjr00/bug.n#250]
Hello,

I am using the Joten_01 configuration example that can be found [here](https://raw.githubusercontent.com/wiki/fuhsjr00/bug.n/Configuration-examples/joten_01.ini) and I want to change the new window position to the top of the stack and remove the display of the battery life, volume, date and time.

Changing `Config_newWndPosition=top` to `Config_newWndPosition=stackTop` does not change the new window position to the top of the stack. It still remains at the top of the list (master).

Changing `Config_readinBat=1` to `Config_readinBat=0` and `Config_readinVolume=1` to `Config_readinVolume=0` removes the battery life and volume indicator respectively. However changing `Config_readinDate=1` to `Config_readinDate=0` and `Config_readinTime=1` to `Config_readinTime=0` does NOT remove the date and time.

Can anyone reproduce this? Attached is my config file.
[config.txt](https://github.com/fuhsjr00/bug.n/files/4543014/config.txt)

**Comment by joten** [comment]
From your `config.txt` it seems you left the lines you changed commented out, therewith inactive. You will have to remove the `;` at the beginning of the line.

**Comment by javesar** [comment]
Understood, that fixes the issue, thank you! This program is amazing, thank you so much for developing it!!
