### ISSUE TITLE
bug.n hotkey won't work on system window like task manager window?

### ISSUE THREAD

**Issue by lubocheng** [fuhsjr00/bug.n#251]
>all the hotkeys i configed in bug.n won't work when meet system windows, like task manager window.
for example, I set `#q` to close window while on task manager, this hotkey trigger the system search.

![Snipaste_2020-04-29_10-52-56](https://user-images.githubusercontent.com/3746672/80858378-8d77c180-8c8b-11ea-8668-00342fc80a31.png)

![Snipaste_2020-05-02_15-45-18](https://user-images.githubusercontent.com/3746672/80858473-00813800-8c8c-11ea-8653-805c0255226f.png)

**Comment by joten** [comment]
Task Manager is an app, which is not run in the user‘s context as bug.n is. Either you will have to activate a different window when controlling bug.n, or you will have to run bug.n itself as administrator allowing it to moveable resize Windows system apps, too.

**Comment by lubocheng** [comment]
Many thanks, i see it
