### ISSUE TITLE
Mouse Resetting to the middle of the screen on my second monitor.

### ISSUE THREAD

**Issue by Werner1201** [fuhsjr00/bug.n#252]
Firstly, I want to thank you for working on this program, since I'm learning I3wm I wanted to use hotkeys to work with windows too. That said, I'm planning on releasing a i3wm shotcut file to people to use.
Going to the point of the issue, everytime I use Firefox on my second monitor and I start loading a new web page, my mouse is reseting to the middle of the screen and when I'm on a page that is dynamicly generating content the mouse goes nuts. I'm going to send my config file so you can take a look if there's any config wrong there. I may also Add that I compliled the program on my PC, so Idk if it does anything different.
[Config.txt](https://github.com/fuhsjr00/bug.n/files/4651390/Config.txt)

**Comment by joten** [comment]
My guess is that bug.n detects a window being activated, when a web page is loaded or reloads content, and with `Config_mouseFollowsFocus=1` it resets the mouse Pointer to the middle of the than active window.

**Comment by Werner1201** [comment]
Then, Should I remove the focus ? I'll try it later, than I'll give some
feedback

Em qui, 21 de mai de 2020 14:22, joten <notifications@github.com> escreveu:

**Comment by Werner1201** [comment]
I guess this fixed the problem. thanks for your help
