### ISSUE TITLE
activate only windows in Stack area

### ISSUE THREAD

**Issue by ertwro** [fuhsjr00/bug.n#253]
Hi. 
I don't know if is possible to add a hotkey to only move between windows in the stack area.
I know there's the function ```View_activateWindow(0, +1)``` which changes between windows in the active tag.
I know there's ```View_activateWindow(1)``` to change to the master area, so maybe is just a syntax thing I'm no seeing here.

For instance if my configuration is:
```ahk
View_#1_#2_layout_#2=2
View_#1_#2_layoutAxis_#2=1
View_#1_#2_layoutAxis_#3=3
```
I want to be able to move only between the six windows in this hypothetical stack. <kbd>1x1|6</kbd>

**Comment by joten** [comment]
Currently, there is no given possibility for doing this.

Theoretically, you may copy `View_activateWindow` and change the line, which is 73 in src/View.ahk, to `i := Manager_loop(j, d, View_#% Manager_aMonitor%_#%v%_layoutMX * View_#% Manager_aMonitor%_#%v%_layoutMY, wndId0)`, but will have to make sure, that there are enough windows in the stack.

**Comment by ertwro** [comment]
Oh, good to know. I thought I wasn't understanding the syntax.
I tried replacing the ```1``` in loop of line 73 with ```
 View_#%Manager_aMonitor%_#%v%_layoutMX * View_#%Manager_aMonitor%_#%v%_layoutMY``` without success as the same behavior of regular ```View_activateWindow``` occurs.

If I try, for instance, the following instead
```ahk
 View_#%m%_#%v%_layoutMX * View_#%m%_#%v%_layoutMY
```
the result is It only moves between the top and bottom window in the stack. Which is an interesting behavior when I have only two windows there, but there's no cycling through the stack.

I mean, while the stack area is in monocle layout I get a little disoriented and is a small annoyance but it keeps getting on my nerves.

**Comment by ertwro** [comment]
Couldn't make this work but even only top and bottom of the stack is better than before. Thanks for the help.
