### ISSUE TITLE
Broken links in Wiki (config files and pdf tutorials)

### ISSUE THREAD

**Issue by o0morgan0o** [fuhsjr00/bug.n#256]
First thank you for this very interesting project.

The links for the pdfs in https://github.com/fuhsjr00/bug.n/wiki/Tutorial-00.-Overview seems broken. Also the configuration examples (.ini files) can't be downloaded from here : https://github.com/fuhsjr00/bug.n/wiki/Configuration-examples 
Even if I am used to i3, i am still confused with the basic raw config, and to access to these examples of config would be a great help.

**Comment by aevdokimenko** [comment]
@o0morgan0o , could you elaborate a bit on the issues you see as I'm able to download both pdfs and ini files? Screenshots and specific urls to the broken files as they resolved in your browser would be especially helpful.

**Comment by o0morgan0o** [comment]
Oh sorry, problem was from my side, resources were blocked by my router after double check. problem solved. Thanks
