### ISSUE TITLE
shareX doesn't follow the rules 

### ISSUE THREAD

**Issue by zen-quo** [fuhsjr00/bug.n#258]
Hi, added this to config.ini:
> Config_rule=WindowsForms10.Window.8.app.0.36c601b_r12_ad1;.*;;0;0;0;1;1;0;

^to both the main window and recording frame to stay in one view.

reloaded bug.n with `win` `ctrl` `R`, quitted shareX. reopenned shareX and brought up the info:
>ID: 0xb0466
class:	WindowsForms10.Window.8.app.0.36c601b_r12_ad1
title:	ShareX 13.1
process:	ShareX.exe [5644]
style:	0x16CF0000
metrics:	x: 562, y: 285, width: 860, height: 510
tags:	--
Config_rule=WindowsForms10.Window.8.app.0.36c601b_r12_ad1;ShareX 13.1;;0;;;;;0;
(this is the main window)

the recording frame has same class - different title. shows this rule:
> Config_rule=WindowsForms10.Window.8.app.0.36c601b_r12_ad1;ShareX - Ekran kaydetme;;0;;;;;0;

when no rule is set for it, it tiles like other apps. any idea why `;;0;0;0;1;1;0;` isn't applied?

**Comment by ertwro** [comment]
Sometimes when your programs update they change a portion of the folder's name.
```
Config_rule=WindowsForms10.Window.8.app.0.*;ShareX.*;;0;0;0;1;1;0;
```
Although, by using that setup the frame is gonna be managed by the layout and the windows are gonna be over each other.
maybe a better alternative would be:
```
Config_rule=WindowsForms10.Window.8.app.0.*;ShareX.*;;0;0;0;0;0;1;
Config_rule=WindowsForms10.Window.8.app.0.*;Screen.*;;0;0;0;0;0;1;
```

**Comment by zen-quo** [comment]
Thanks for the reply! I added those two rules and shareX is still visible on all the views. But the rule is applied according to the info: 
> Config_rule=WindowsForms10.Window.8.app.0.36c601b_r12_ad1;ShareX 13.1;;0;;;;;1;

Without any rules for it, main window and the recording frame seems to stay in one view but when I switch to another it continues to record there. So I'm guessing it's not possible to record in one view and continue to when user is switched to another.

**Comment by ertwro** [comment]
No, you can't record a hidden tag. A tag not visible is not being rendered by your graphics card. Even a Windows Workspace doesn't render inactive workspaces by the native windows manager. The whole idea of something like ShareX or OBS is to capture a **visible Area**(same tag). If you want to record a process regardless of position you need a **process** recording tool (like ffmpeg) and a process that outputs to stdin, not an **area** recording tool. You can record a window that's covered by another window in in the same tag, you could use the monocle layout and something like OBS.
ShareX follow the rules.

**Comment by zen-quo** [comment]
Ah I got it now. Thank you again for such a through answer, it concludes this issue.
