### ISSUE TITLE
Bug for commit SHA-1: 2fcad88aa935ccbfef80740f01ed22cfa99b6c5d

### ISSUE THREAD

**Issue by franckspike** [fuhsjr00/bug.n#27]
This commit makes about all of the hidden windows of my system to become visible windows.

The taskbar becomes full, #+i also list them all.

**Comment by joten** [comment]
Unfortunately it wasn't the last commit, which caused the problem; I noticed it, too. I committed a workaround, which circumvents this bug, but also produces a new, already known bug (missed shell messages).

Currently I am not in a fit state and won't be able to work on bug.n.

**Comment by franckspike** [comment]
I think you didn't push on github :)

**Comment by joten** [comment]
Right. The first push failed.

**Comment by franckspike** [comment]
Thank you

**Comment by franckspike** [comment]
The bug still happened with the fix though

**Comment by joten** [comment]
I tried a different approach to shell-message-handling. -- It didn't work out. In the end I couldn't fix the resulting problems and therefor reverted back to the point, where it seemed to work more reliably.

Please have a look, if the above problems still exist in the current development version.

**Comment by joten** [comment]
If possible, please test the current development version (.exe is up-to-date). Is the bug still crawling about?
