### ISSUE TITLE
A cheatsheet, and a macro for showing it in the screen.

### ISSUE THREAD

**Issue by spitfire-hash** [fuhsjr00/bug.n#271]
Yeah as the title says, I think it would be great if there was a cheat sheet(a pdf or something, just showing all the shortcuts, and briefly explains what each of them does).

For example in Discord there's a shortcut <kbd>ctrl</kbd>+<kbd>/</kbd> for showing a cheat sheet which contains all the stuff a user needs. If there was a similar thing in `bug.n` it would be great. Like pressing `#h` could bring the cheat sheet.

If there's possibility that could happen I can create a pull with that cheat sheet, if you need.

**Comment by joten** [comment]
There is a PDF in the documentation of the latest release under bug.n-9.0.2/doc/Cheat_sheet/ which lists the default hotkeys. Although it is not linked to a hotkey like `^ /::Run, open doc\Cheat_sheet\cheat_sheet.pdf`.

It is created during the build process with [tools/build.ahk](https://github.com/fuhsjr00/bug.n/blob/0e912908e5cebc0eba9a345cc360140b5cc7d585/tools/build.ahk#L36) using pandoc (if installed).

**Comment by spitfire-hash** [comment]
@joten I don't have the `pandoc` installed so it didn't build for me, also I am using `bug.n` from its binary. Is there a place that I can get that cheat sheet?

**Comment by joten** [comment]
You may download the latest release, currently [bug.n v9.0.2](https://github.com/fuhsjr00/bug.n/releases/latest); the cheat sheet is located in the directory `doc/Cheat_sheet/` of the archive. This cheat sheet is also compatible with the current master.

**Comment by spitfire-hash** [comment]
Thank you!
