### ISSUE TITLE
anyway to disable tiling functionality?

### ISSUE THREAD

**Issue by junguler** [fuhsjr00/bug.n#272]
i like the option to not have borders in any programs but i'm not really a fan of the tiling option, is there anyway to disable only that part of bug.n?

**Comment by joten** [comment]
You may disable dynamic tiling by setting the line `Config_dynamicTiling=0` in Config.ini; it leaves bug.n with manual tiling.

**Comment by junguler** [comment]
thank you

**Comment by junguler** [comment]
hi again, i noticed when i close bug.n it tiles every open window and exits, is there anyway to disable this behavior?

**Comment by joten** [comment]
Nope, not while using the executable; you would need to alter the code. The tiling on exit is done in [line 167 of bug.n/Manager.ahk](https://github.com/fuhsjr00/bug.n/blob/0e912908e5cebc0eba9a345cc360140b5cc7d585/src/Manager.ahk#L167) and insures that all windows are accessible in case bug.n did some misplacement when the monitor configuration was flawed.

In an no-tiling version one could have the following code 
```
;; Restore window positions and sizes.
If (Config_dynamicTiling == 1) {
  Loop, % Manager_monitorCount
  {
    m := A_Index
    Monitor_#%m%_showBar := False
    Monitor_#%m%_showTaskBar := True
    Monitor_getWorkArea(m)
    Loop, % Config_viewCount
    {
      View_arrange(m, A_Index, True)
    }
  }
}
```

**Comment by junguler** [comment]
thank you for the detailed response, feel free to close this issue whenever you like.
