### ISSUE TITLE
Visual Studio 2012 not managed

### ISSUE THREAD

**Issue by franckspike** [fuhsjr00/bug.n#28]
Since after feb 17th, especially with the feb 23th commit,

Visual Studio 2012 (.NET WPF) apear on all views of a monitor.

Sometimes my xplorer^2 too, by when I terminate it, then restart it it appears to fix this.

Google Chrome sometimes do the same thing...

**Comment by franckspike** [comment]
Also some hidden windows become visible, even if their application owner didn't make them visible.

**Comment by joten** [comment]
I tried a different approach to shell-message-handling. -- It didn't work out. In the end I couldn't fix the resulting problems and therefor reverted back to the point, where it seemed to work more reliably.

Please have a look, if the above problems still exist in the current development version.

**Comment by franckspike** [comment]
Fixed (VS2012 is not managed)
