### ISSUE TITLE
Gap managing new frames of Emacs on Windows 8.1

### ISSUE THREAD

**Issue by louy2** [fuhsjr00/bug.n#29]
I am using Windows 8.1 64-bit with GNU Emacs 24.4 64-bit Windows binary.

The problem is when I create new frames with `C-x 5 2`, all the resulting new frames have a top margin shown in the screenshot.

![bugn_gap_emacs_new_frame](https://cloud.githubusercontent.com/assets/2263580/6382273/429fdee0-bd15-11e4-8ea7-c452e82908c0.PNG)

The only one without that margin is the original frame opened with `runemacs`, the second in the stack.

**Comment by joten** [comment]
As far as I know, the problem is, that Emacs does manage its own windows, i. e. Emacs sets the window size. Due to the line-oriented GUI with a fixed font size, line height and number of lines, the resulting window height only can have discrete values. Mine does look like the following:

![Emacs screen](https://cloud.githubusercontent.com/assets/6839361/6541440/c5c91572-c4cf-11e4-991b-ef860c7b8e5c.png)

What size does the original frame get, when you move it (Win+Shift+Up) through the stack?

**Comment by louy2** [comment]
![bugnemacswindowsize](https://cloud.githubusercontent.com/assets/2263580/6543836/3f6fad1a-c4fc-11e4-9d59-77f4d3566b96.PNG)

Interesting. The original frame retains its full size when moved, and actually displays different number (I suspect that's a fraction?) of lines. On the other hand the created frame indeed only displays discrete number of lines.

But if you look at the original screenshot the top right frame displays a half line at the end when the original frame, below it, displays whole lines. The frame in the main position, being created, also displays a half line, although empty, at the end.

**Comment by joten** [comment]
I am using Windows 8.1 64-bit with EmacsPortableApp 24.3. I am not using Emacs productively.

In my scenario all frames behave the same way, the original one, too. And I do not get any partially visible lines, only whole lines.

Can you post the window information for the different frames (Win+I in the default configuration)?

**Comment by louy2** [comment]
The following info are collected when the designated frame is in main position.

Original frame:
```
ID: 0x30288
class:	Emacs
title:	index.js
process:	emacs.exe
style:	0x170F0000
metrics:	x: -2, y: -2, width: 883, height: 904
tags:	1

Config_rule=Emacs;index.js;0x170F0000;1;1;1;0;0;0;Maximize
```

Created frame:
```
ID: 0x60298
class:	Emacs
title:	index.js
process:	emacs.exe
style:	0x160F0000
metrics:	x: 0, y: 8, width: 881, height: 894
tags:	1

Config_rule=Emacs;index.js;0x160F0000;1;1;1;0;0;0;
```

It seems the only difference is the additional "Maximize" in the main frame. Probably because I use `runemacs -mm` to auto-maximize it on start. I have confirmed that `runemacs` normally produces the same result as yours.

**Comment by louy2** [comment]
Adding the following line to `Config.ini` has eliminated all gaps between Emacs frames.
```
Config_rule=Emacs;.*;;1;0;0;0;0;0;maximize
```

**Comment by joten** [comment]
I added the rule to the documentation (doc/Configuring_rules.md).

Thanks for your help.
