### ISSUE TITLE
An optimized interface

### ISSUE THREAD

**Issue by eqan** [fuhsjr00/bug.n#293]
I saw bell's branch who apparently made the taskbar more accessible instead of creating a new one, is this possible?? as I had compiled and ran the application but nothing worked.
![image](https://user-images.githubusercontent.com/61124752/172055679-947b8d34-bcfe-455b-b85b-a8ff4759b599.png)

Link to the branch: https://github.com/belljames/bug.n.simplified

**Comment by joten** [comment]
In belljames branch I could not see any changes to the src files, only to the README. From the description the following Config.ini could make bug.n look like it:
```
Config_horizontalBarPos=36
Config_verticalBarPos=Tray
Config_barWidth=208
Config_spaciousBar=1
Config_fontSize=10
Config_readinDate=0
Config_readinTime=0
Config_showTaskBar=1
Config_viewNames=1;2;3;4;5
Config_mouseFollowsFocus=0
Config_rule_#1=.*;.*;;1;0;0;0;1;1
Config_rule_#4=QWidget;.*;;1;0;0;0;1;1;
Config_rule_#5=SWT_Window0;.*;;1;0;0;0;1;1;
Config_rule_#6=Xming;.*;;1;0;0;0;1;1;
Config_rule_#8=AdobeFlashPlayerInstaller;.*;;1;0;0;1;1;1;
Config_backColor_#1=0;0;0;0;0;0;0;0;0
Config_foreColor_#1=0;0;0;0;0;0;0;0;0
Config_fontColor_#1=ffffff;ffffff;0;0;0;0;0;0;0
Config_backColor_#2=0;;;;;;;0;0
Config_foreColor_#2=0;;;;;;;0;0
Config_fontColor_#2=ffc000;;;;;;;0;0
```

But I guess the idea was to reduce the code -- perhaps making it less complex and more maintainable.

`Config_verticalBarPos=Tray` integrates the bug.n bar into the Taskbar, but it is only an overlay (inlay?); therefor the configuration above hides the first Taskbar icons and [centering those](https://www.howtogeek.com/736658/how-to-center-your-windows-10-taskbar-icons-like-windows-11/) or setting `Config_horizontalBarPos` to a different value whould fix this.

**Comment by eqan** [comment]
Got it thank you.
