### ISSUE TITLE
how to run Main.ahk

### ISSUE THREAD

**Issue by azinsharaf** [fuhsjr00/bug.n#297]
Hi, I read all the documents and Issues section but still can't run it on my machine. I can't run the exe file because of organization policy. How can I run the `Main.ahk` file?

![image](https://user-images.githubusercontent.com/10101468/183267763-2a7544b5-d00e-4728-b789-9146ded00adb.png)

I have `AutoHotKey` installed on my machine as it is working fine with other `ahk` scripts (not this repo)

**Comment by DWTW321** [comment]
I can see that Bar.ahk is in the same folder so it should be recognised. It could be a permissions issue. Where have you saved the src folder? Have you tried running Main.ahk as an admin? Also what version of AutoHotKey are you using?

**Comment by DWTW321** [comment]
If it still doesn't work you could try editing Main.ahk and replace #Include Bar.ahk with #Include %A_ScriptDir%\Bar.ahk

**Comment by azinsharaf** [comment]
@DWTW321 
Thanks for the help. Including `%A_ScriptDir%\` fixed the issue. Can we have this configuration as the default in the repo?

I have full access to the folder. I don't have local admin account s can't run it as admin.

**Comment by DWTW321** [comment]
I'm glad it's working, I'm not the maintainer, I just saw your issue and thought I could help out.

**Comment by azinsharaf** [comment]
@DWTW321  Thanks again. I keep this open so the maintainers can answer it.

**Comment by fuhsjr00** [comment]
Thank you very much, @DWTW321. If someone wants to post a pull request, I would be happy to look at it. I haven't really used Windows in a decade now, so I wouldn't be able to test it. Are @joten or @x29a still around?

**Comment by DWTW321** [comment]
@fuhsjr00  I have some time tomorrow, I'll see if I can do it.

**Comment by zadrdy** [comment]
how to start main ahk if i getting error at line 25 i just wanna use dolph sol 😭
