### ISSUE TITLE
How to activate only the top bar and virtual desktops?

### ISSUE THREAD

**Issue by cammpion** [fuhsjr00/bug.n#298]
Hello.
Newbie here in everything. I love bug.n, it's amazing.

I was wondering if there is a way to just use the top bar and virtual desktops. basically kill bug.n and just leave those functions.
Can it be done?

Thank you

**Comment by DWTW321** [comment]
`Config_showBar=1` (this will show the bar) 

`Config_layout_#3=><>;`  (the symbol can be anything but make sure its blank after the semi colon, the blank parts means you want floating behaviour)

`Config_layoutCount=1` (to make sure that the only layout available is floating)

`Config_viewNames=1;2;3;4;5;6;7;8;9`  (here you can define the name and number of workspaces/virtual desktops)

And that should work, you should now have the workspaces and the top bar without any tiling. If you want to hide the Windows task bar you can use `Config_showTaskBar=0` you can then use Win+Space to toggle the task bars visibility.

Hope that helps

**Comment by cammpion** [comment]
Thank you!

**Comment by floweringnights** [comment]
> Thank you!

When you're done with solving the problem, close your issue, please!
