### ISSUE TITLE
Cannot control X forwarded windows. 

### ISSUE THREAD

**Issue by OAshkar** [fuhsjr00/bug.n#299]
Hi,

I am using MobXterm to ssh through a server, then plot figure in any software, let's say R. Whatever window I got is float by default. I can only make is full screen, but cannot tile anywhere. 

The info window is pasted here. 

```
ID: 0x4b0d12
class:	moba/x X rl
title:	R Graphics: Device 2 (ACTIVE) [hidden]
process:	XWin_MobaX.exe [12412]
style:	0x96CF0000
metrics:	x: 208, y: 220, width: 687, height: 710
tags:	--

Config_rule=moba/x X rl;R Graphics: Device 2 (ACTIVE);;0;;;;;1;
```

I would like to use bug.n in my workflow. 

Thank you,

**Comment by DWTW321** [comment]
I haven't ever used MobXTerm before but for VcXsrv I put this in my config and it started working.
`Config_rule=vcxsrv/x X rl;*;;1;0;0;0;1;0;`
So you can maybe try the following.
`Config_rule=moba/x X rl;*;;1;0;0;0;1;0;`
or
`Config_rule=moba/x X rl;*: *;;1;0;0;0;1;0;`

Let me know if that works, if not I can download MobaXterm and troubleshoot for you.

**Comment by OAshkar** [comment]
Thank you for your quick response. It is tiling now! I will close this.
