### ISSUE TITLE
Unable to use Main_reload to reload configuration

### ISSUE THREAD

**Issue by webframp** [fuhsjr00/bug.n#31]
using latest dev exe from eb4395fbea4b9a3f35a51fe5ec1f1928eced4635

trying to reload configuration using `#^r::Main_reload()` gives this error:

![bugn reload](https://cloud.githubusercontent.com/assets/774378/6526474/4ba8cd04-c3e0-11e4-89f1-e4836893e9ab.png)

full reload with `#^+r::Reload` works fine

**Comment by joten** [comment]
I took the easy way out, by deleting the function. It is redundant with `Config_autoSaveSession` being able to restore the window states.

**Comment by webframp** [comment]
Nice, works for me. Thanks :thumbsup:
