### ISSUE TITLE
Screenshots on README

### ISSUE THREAD

**Issue by gutierri** [fuhsjr00/bug.n#39]
:+1:

**Comment by joten** [comment]
Well, this is the second request for screenshots in the README. Personally, I like the text without pictures, but ...

If this issue gets :+1:.comments from at least 100 different users, I will comply.

**Comment by franckspike** [comment]
:+1:  at the end, before installing it, seeing it is helpful to decide

**Comment by gutierri** [comment]
@franckspike :+1:

**Comment by louy2** [comment]
:+1:

**Comment by bornskilled200** [comment]
:+1:

**Comment by louy2** [comment]
Just found this extension from Bountysource dealing with such voting: https://www.bountysource.com/extension

**Comment by Chadehoc** [comment]
I personnaly like text, too, but I don't think it's a request for "more images in the doc", just that it could be useful to see what a tiled layout "looks like in Windows".

The look of it is very similar to what screenshots you can find for Xmonad or dwm, but _the decoration of windows is still managed by the Windows WM._ So bug.n has not the same extent as a Linux WM, it just manages the layout and workspaces, and the result is clean. However, via bug.n you can tell the Windows WM to hide or show the window title, or make the borders thinner, hide or show the taskbar...

Tiling is so unusual in Windows that I think only one or two screenshots in the README would be enough. I admit I was dubious (but full of hope) when I first tried bug.n... and I'm still amazed at how this works well, being just a thin layer, that can be stopped and restarted in a wink. Using AutoHotKey was a great idea.

My :+1: then.

**Comment by Volker-E** [comment]
:+1:

**Comment by ralesi** [comment]
+1

**Comment by CMCDragonkai** [comment]
+1 of course!

**Comment by subnomo** [comment]
:+1:

**Comment by huffstler** [comment]
:+1:

**Comment by palra** [comment]
:+1:

**Comment by joten** [comment]
Well, although there are not 100 :+1: I added the screenshot.
