### ISSUE TITLE
Command window (`#y`) little bugs

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#41]
First mentioned in #26 but precised here.

I work with two monitors, synchronized by `Config_syncMonitorViews=1`.
* The command window is only available on monitor 1. Using `#y` from any monitor pops it up on monitor 1 (which would be acceptable for me). Clicking on the bar shebang only works on monitor 1.
* When called by `#y`, the command windows pops up under the window, so it practically works only when the view is empty. I think it is under because sometimes I can see the flicker; maybe it just closes quickly.

**Comment by joten** [comment]
I could not reproduce the problem yet. But perhaps the latest change already fixes the bug.

**Comment by Chadehoc** [comment]
> I could not reproduce the problem yet. But perhaps the latest change already fixes the bug.
Partially. Now `#y` from monitor 1 works pops up over the windows, but from monitor 2 it does nothing (as clicking the shebang), even with empty views. So to sum it up, from monitor 1 all works well, and from monitor 2 nothing works.

**Comment by Chadehoc** [comment]
I confirm that the latest change above has fixed it for me.
