### ISSUE TITLE
Force Not Maximize Window

### ISSUE THREAD

**Issue by louy2** [fuhsjr00/bug.n#43]
Firefox, when the view contains only it and it is maximized, only fills in the space left by the taskbar and the status bar, regardless whether they are hidden or not. Only when not maximized does it fill the whole screen. So I wonder if there is a way to force window not to maximize.

**Comment by joten** [comment]
502a4e5232527d9972e0367c83fbf23475c5b504 possibly fixes the bug; I only tested it on a single monitor system.

**Comment by louy2** [comment]
I only use a single monitor for now. It has fixed the problem for me.
