### ISSUE TITLE
How to force a misplaced window to be re-tiled?

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#45]
I would enjoy a way to force the re-tiling of a window when its position is bad. It happens regularly when windows change their own position and do not e.g. take well into account the taskbar that I use vertically.

My main example: when the Delphi IDE switches to/from execution mode, it resizes itself, and becomes too large for the workarea.

My current workaround:
* `#+d` to show the bar
* click on the button to make it smaller
* `#+f` twice to force it to be retiled from a non-fullscreen position

Some details:
* just `#+f` twice doesn't work. It seems that when already thought well-tiled, re-tiling does nothing, so I have to force a resize first. This solution would be enough for me if it worked.
* resizing with `#+s` doesn't work in this case (cursor ok but window refuses to resize), so I have to use the show-bar + click thing. I don't know why; it usually works.

**Comment by louy2** [comment]
Have you tried `#t`?

**Comment by Chadehoc** [comment]
> Have you tried `#t`?
Of course. Any switch-like behaviour doesn't work (`#m` `#t` for example), it seems one has to "inform" that positioning is wrong by actually changing something, as if bug.n would only react to a change.

**Comment by louy2** [comment]
Could you provide the information of the window when it's off-tile?

**Comment by Chadehoc** [comment]
> Could you provide the information of the window when it's off-tile?

Bad:
```
class:	TAppBuilder
style:	0x170F0000
metrics:	x: 88, y: 12, width: 1848, height: 1216
Config_rule=TAppBuilder;EdT32 - Delphi XE6;;1;1;1;0;0;0;maximize
```

Good (after forced re-tiling):
```
class:	TAppBuilder
style:	0x160F0000
metrics:	x: 88, y: 12, width: 1832, height: 1188
Config_rule=TAppBuilder;EdT32 - Delphi XE6;;1;1;1;0;0;0;
```

Interesting indeed: the style has changed, and the rule in the bad case says `maximize`!

**Comment by louy2** [comment]
Maybe related to #43 , similar problem I had with Firefox.

**Comment by Chadehoc** [comment]
> `Config_rule=TAppBuilder;EdT32 - Delphi XE6;;1;1;1;0;0;0;maximize`
Is it actually normal to have a non-floating window in maximize mode? Would this be accepted for a rule? (I would only make sense of it for floating windows.) Then maybe this contradictory setting is responsible for bad behaviour?

**Comment by louy2** [comment]
It's not normal to have non-floating windows in maximize, but it certainly should work. I use maximize to eliminate space not filled by normal GTK Emacs and side-edges of FIrefox.

**Comment by joten** [comment]
Sorry for the late response. -- Better late than never?

My questions would be:
* What do you mean by "click on the button to make it smaller"? The restore button, the one between "minimize" and "close" in the title bar?
* Is the "EdT32 - Delphi XE6" window the only one on the view?
* If it is not the only window on the view and you are in tile layout, what happens if you do `#+Down::View_shuffleWindow(0, +1)` or `#+Up::View_shuffleWindow(0, -1)`?

**Comment by Chadehoc** [comment]
> Sorry for the late response. -- Better late than never?

You're welcome! :^)

It seems that this issue was much less annoying the last few months. I cannot tell since when for sure, however someday the windows behaviours changed: instead of reacting immediately to other windows disappearance, they didn't react until for exemple focusing them or issuing another "active" bug.n shortcut. Since then, all layout mistakes are easily fixed by for example cycling through layouts.

To make it short, bad layouts still happen but are more easily fixed now (I used to regularly wipe out the `_Layout` and `_WindowState` files, now rarely).

> My questions would be:
> 
> * What do you mean by "click on the button to make it smaller"? The restore button, the one between "minimize" and "close" in the title bar?

Yes, that was the quickest way to change the window size using the mouse (keyboard-only shortcuts didn't work the same). Mouse-resizing did the trick, too, I think.

> * Is the "EdT32 - Delphi XE6" window the only one on the view?

Yes.

> If it is not the only window on the view and you are in tile layout, what happens if you do #+Down::View_shuffleWindow(0, +1) or #+Up::View_shuffleWindow(0, -1)?

I think I remember that even sending it to the other screen and back again, it got back the same bad position. Every attempt to cycle through states that didn't involve resizing and retiling didn't work. I think it internally had recorded this as the good state.

**Comment by joten** [comment]
You may add the following line to your `Config.ini` and be able to reset the buggy window with one hotkey: `Config_hotkey=#^o::Manager_override(1;0;0;0;0;0;restore)`

As far as I can see, this issue is not a bug in bug.n but in the Delphi IDE, which tries to manage its own window. Therefor the only solution I can offer is the workaround above.

**Comment by Chadehoc** [comment]
> You may add the following line to your Config.ini
> and be able to reset the buggy window with one hotkey

Thanks !!

> As far as I can see, this issue is not a bug in bug.n but
> in the Delphi IDE, which tries to manage its own window.

Yes, of course. I was aware of that, I was indeed looking for a
workaround (the initial issue was really a question, not a bug
report).

Delphi is not the only app that tries to manage its windows, this will
e handy elsewhere, thanks.
