### ISSUE TITLE
Some windows ignoring placement completly

### ISSUE THREAD

**Issue by E-Chan** [fuhsjr00/bug.n#47]
Using bug.n and really happy with it, but often i'll find a program that will completly ignore bug.n's placement like Naver Line's chat program, not only will it show in all desktops but it won't resize or organize. Any way to fix this?
Thanks

**Comment by louy2** [comment]
Check if it's managed by bug.n with `#i`. Check the last line against [Configuring rules](https://github.com/fuhsjr00/bug.n/blob/master/doc/Configuring_rules.md).

If it's not managed, you can force it to be managed following the instructions [here](https://github.com/fuhsjr00/bug.n/blob/master/doc/Customization.md).

**Comment by joten** [comment]
No further reply. The issue seems to be solved.
