### ISSUE TITLE
Made a cheatsheet with all the shortcuts in the documentation

### ISSUE THREAD

**Issue by palra** [fuhsjr00/bug.n#54]
Check it out : http://www.cheatography.com/gamer204/cheat-sheets/bug-n/

**Comment by huffstler** [comment]
Couldn't you have made a pull request or something instead of opening an issue?

**Comment by palra** [comment]
I didn't acually modified the code, so I didn't know where to put it. You think that I should do a PR so ? Making a link to the cheatsheet in the README or in the docs, or both ?

**Comment by huffstler** [comment]
I think it would be a better idea, but I'm also not the owner of the repo lol, not sure how he/she likes stuff organized. I do think it would be beneficial to have a user submitted and edited "Cheat-Sheet" that brings some aspects of bug.n down to lay terms. I'll see if I can open an issue asking where something like this can be put for the benefit of future users. (Or you can if you want to)

**Comment by fuhsjr00** [comment]
That looks pretty useful. I tend to let @joten decide on these things, but we can at least include a link in the doc.

Pull requests are really easy to deal with if kept to-the-point.

**Comment by joten** [comment]
@palra Thanks for your work, I like it.

> we can at least include a link in the doc. Pull requests are really easy to deal with if kept to-the-point.

Right he is.

> I didn't acually modified the code, so I didn't know where to put it.

The documentation is kept as source code (markdown), too; therefor you may create some kind of source file (markdown or *wiki?), from which the cheat sheet could be generated.

Top-notch would be to use markdown, e. g. as in [this file](https://github.com/pklaus/CheatSheets/blob/master/cheatsheets_markdown/vim.md). (I only had a quick glance at it.) The cherry on the cake would be to create the CSS file, that goes with it. -- I wrote my CV in markdown, using pandoc to convert it to HTML and style it with CSS. -- But I don't think GitHub allows the inclusion of CSS file references in the automatically displayed markdown files. Nevertheless, the markdown could be displayed by GitHub as usual, and the generated HTML with CSS could be used to create a printable cheat sheet.

**Comment by palra** [comment]
If the cheatsheet is transpiled to markdown, then the job is already done ! In fact, I just read the `doc/Default_hotkeys.md` file in order to create my cheatsheet.
I began by creating this cheatsheet for myself, and then I though it would be a good idea to share it with you, but I don't have any idea how it can be used ... It doesn't even need to be included in the docs if that's the problem !

**Comment by joten** [comment]
> If the cheatsheet is transpiled to markdown, then the job is already done

Well, I couldn't resist and tried to create the cheat sheet more or less reproducible from `bug.n/doc/Default_hotkeys.md` with the result being [this](https://github.com/fuhsjr00/bug.n/blob/master/doc/Cheat_sheet/cheat_sheet.pdf).

**Comment by palra** [comment]
Wouldn't the document be more readable if  `#`, `!`, `^` and `+` were replaced with their appropriate `<kbd>` tags in the HTML ?

**Comment by joten** [comment]
On the one hand you are right, but on the other hand the short notation saves space. I may try to shorten the text a bit more, currently it is the original text stripped of additional comments. I already set the font to a small size.

But have a try, it's a bit fiddly, therefor it takes time to find the right adjustments.

**Comment by joten** [comment]
I updated the cheat sheet with commit fc0ec399e4c5fd83b5f4698e415ebb2d4a1f3ee3.
