### ISSUE TITLE
Add developer documentation?

### ISSUE THREAD

**Issue by ctjhoa** [fuhsjr00/bug.n#57]
Hi,
Please can you add developer documentation on "how to debug" and "how to build the project" ?
I'm very interested in this project but I'm totally noob with autohotkey and I don't know how to start.
Thanks

**Comment by louy2** [comment]
What you need should all be here: http://ahkscript.org/
Making a script into an exe is achieved by http://ahkscript.org/docs/Scripts.htm#ahk2exe

**Comment by ctjhoa** [comment]
Ok thanks !
