### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jcarpoff** [fuhsjr00/bug.n#61]
Hi, bugn.exe on my system uses up most of the resources of one core, though seems to be working and responding well. Is this normal? If not, is it possible to see what's might be keeping it busy in my case, i.e. enabling logging of some sort?

**Comment by franckspike** [comment]
Try erasing (backuping) the ...\AppData\Roaming\bug.n\data\_WindowState.ini file.

**Comment by jcarpoff** [comment]
Ahh, what a difference. Thank you.
