### ISSUE TITLE
Custom Time or Date Format?

### ISSUE THREAD

**Issue by steelet41** [fuhsjr00/bug.n#62]
Is there a way to customize the date and time format shown in the status bar without modifying the source code/rebuilding the executable? I tried a few things in the Config.ini file, but that didn't seem to take.

Ideally I would also be able to create a time widget that shows time in other timezones, not sure how much more difficult that would be.

**Comment by gutierri** [comment]
#63 <- Something like that?

**Comment by steelet41** [comment]
Yes, thank you, that looks like it would solve my problem.

**Comment by gutierri** [comment]
Cool! :)

2015-11-20 13:59 GMT-02:00 steelet41 <notifications@github.com>:
