### ISSUE TITLE
network meter can't display anything above 10MBps

### ISSUE THREAD

**Issue by killerclimax** [fuhsjr00/bug.n#64]
![image](https://cloud.githubusercontent.com/assets/13599743/11394809/ba017d88-93aa-11e5-928f-99ad7cff05ca.png)

**Comment by joten** [comment]
Right you are, the function was a bit simple. I changed it with commit 02708be4f1d8a70a4e431dba36feb79d9023f1a9. I think values up to 999 GB/s should suffice.

Please give it a spin and comment back.
