### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by beaudryj** [fuhsjr00/bug.n#65]
Is there a hot key for cycling through the views? I know windows backspace will take me to the previous, but I would love to cycle through.

**Comment by qijianjun** [comment]
Im looking for the same hotkey, but it seems that there is no functions to do this now.

**Comment by beaudryj** [comment]
That would literally make this the best thing ever

**Comment by joten** [comment]
There is no predefined hotkey, but the functionality is there.

E. g. by adding the following line to your `Config.ini`, you should be able to forward-cycle through the views:
`Config_hotkey=#+Tab::Monitor_activateView(0, +1)`

For more information have look at:
* [the default hotkeys for view management](https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_hotkeys.md#view--tag-management)
* [customizing bug.n](https://github.com/fuhsjr00/bug.n/blob/master/doc/Customization.md)
