### ISSUE TITLE
Windows position rotated across screens with 3 monitors

### ISSUE THREAD

**Issue by webframp** [fuhsjr00/bug.n#66]
I use a [PLP](http://i.imgur.com/kKbffMF.jpg) setup with 3 monitors, one of which is a TV. When bug.n prompts to restore the window layout it seems to forget which Windows are assigned to each screen and they end up rotated such that windows across monitors end up:

```
[1] - [2] - [3]
```

becomes 

```
[2] - [3] - [1]
```

I am wondering if it is because of the first few lines of my config, which I used fine with only a 2 monitor setup:

```ini
Monitor_#1_aView_#2=3
Monitor_#2_aView_#2=3
View_#2_#1_layoutAxis_#1=2.000000
View_#2_#1_layoutMFact=0.650000
View_#2_#3_layoutAxis_#1=2.000000
```

My [full config is here](https://gist.github.com/webframp/604400d7c1314299a01b)

If that's the problem, How would I adjust it?

**Comment by joten** [comment]
In short: No.

The questions are:

1. What exactly does it prompt?
a. "Would you like to restore an auto-saved session?" or 
b. "Would you like to reset the monitor configuration?"

2. If b), did the monitor configuration really change? And what happens, if you say no?
3. What do the Windows display settings indicate, did _they_ change between sessions?

bug.n is depending on AutoHotkey here, i. e. it simple iterates through the number of monitors and uses `SysGet, monitor, Monitor, %m%`. I do not know, if the numbers retrieved by this command are consistent between calls; maybe there is a possibility to sort the monitors depending on there values.

**Comment by webframp** [comment]
> b. "Would you like to reset the monitor configuration?"

This is the message box displayed. If I say no, the windows remain in their current position, pushed to the two side monitors and nothing on the main display.

The monitor configuration mostly likely changes as a result of the main display shutting off and failing to wake up, [the sleep mode issue here](http://tiamat.tsotech.com/4k-is-for-programmers-redux)

**Comment by joten** [comment]
Have a try with the latest version (2a66bf9e276497a2357daee20837ff711cf5943b).

I have very limited capacities reproducing the issue, i. e. just a laptop and one external monitor (next room), which is even less -- from my experience -- than a pc with two external monitors regarding multi-monitor issues.

**Comment by webframp** [comment]
Seems improved, just happened less. Is there some way I could collect for debug information for you?

**Comment by joten** [comment]
It is more a question of precise observation; as far as I understand the issue the following is happening:

1. all in order
2. monitor 2 goes into standby (and all others, too?)
3. reactivating monitor 2 (and all others) by keyboard or mouse action
4. bug.n wants to reset the monitor configuration
5. answering

  a) no results in all windows being moved away from monitor 2
  b) yes sometimes results in disordered monitors

Is bug.n asking more than once to reset the monitor configuration?

If not resetting the monitor configuration bug.n _should_ go on as before, and when doing e.g. a view switch on monitor 2 all windows should be moved where they belong.

**Comment by webframp** [comment]
1. all in order
2. monitor 2 goes to sleep ( it is a tv basically) the others on standby
3. powering on monitoring 2 (with remote), and others wake up by keyboard action
4. bug.n asks to reset

5. a) no, everything is moved away from monitor two
    b) yes, usually results in disorded monitors.

If the time between step 2 and 5b is a short time frame, perhaps 10-15 minutes, it results in ordered windows as expected. If the time is longer, perhaps 1 hour, then it is disordered every time

**Comment by joten** [comment]
5.a) Are the windows already moved when bug.n asks to reset the monitor configuration or is it a result of answering "no"?

-----
> If not resetting the monitor configuration bug.n should go on as before, and when doing e.g. a view switch on monitor 2 all windows should be moved where they belong.

Does this work as expected?

**Comment by webframp** [comment]
It does. If I answer no the windows are not immediately repositioned but when doing a view switch, say mod+2 to mod+1 they are moved into the right location.

**Comment by joten** [comment]
Does commit d445c61fa3226b685dbb46b3f672278de2db556b remedy the issue? The current behaviour of bug.n seems to be sufficient regarding the issue.

**Comment by webframp** [comment]
That change in d445c61 works great for me, thanks for looking into the issue!
