### ISSUE TITLE
On Windows 10, borderWidth > 0 yields a crash

### ISSUE THREAD

**Issue by Chadehoc** [fuhsjr00/bug.n#67]
I just switched to W10 at work, and setting `Config_borderWidth` either in `config.ini` or directly in `Config.ahk` lets the app crash. It actually doesn't seem to start, but then there remains a AutoHotKey process that can only be killed.

This is with the latest master branch.

Note: on W7 the border was thicker, on W10 it is a single pixel wide and the rest looks like padding. I had not tried to change the default border width on W7 because it was ok for me, so maybe this bug is not specific to W10?

EDIT: I had the idea to turn window shading off. Now it doesn't crash, but the `Config_borderWidth` value seems just ignored (1 pixel border whatever I set here).

EDIT AGAIN: it happens to still crash, more randomly and "in use" (before removing shadows it didn't start correctly, now it does but crashes after some time). I had to remove `Config_borderWidth`from my config again.

**Comment by Chadehoc** [comment]
Workaround: I managed to change the window borders and padding using WinAeroTweaker, and bug.n just follows. It seems that the bug.n (AutoHotKey?) specific commands for that don't work in Windows 10 because there is a "native" (but hidden) way instead.

**Comment by joten** [comment]
Hm, strange. I always had `Config_borderWidth=2` and `Config_borderPadding=0` in my `Config.ini` and never had a problem. Currently I am using WIndows 10 at home and at work. Previously I used Windows 7 and 8, no problem either.

Just a hunch, which version of AutoHotkey are you running? Mine is 32-bit/utf-8; since I do 'compile' the program as 32-bit, I am using it as such. Can you reproduce the problem with the executable?

**Comment by Chadehoc** [comment]
Yes, running `bugn.exe` gives the same crash (in the log file : after processing the  hotkeys, and before the `=== Running ===` header that usually follows, and I see no `forgetting this window` messages either, but these are more random).

I usually use ahk 1.1.22.09 (64 bits) by directly launching `Main.ahk` with my config directory as argument. I'm currently using commit 2a66bf9.

**Comment by titepweb** [comment]
I have 

- Config_borderWidth=5

- Config_borderPadding=2

in my config.ahk , but it doesn't show the rectangle border too.

**Comment by marchoutlook** [comment]
I have

Config_borderWidth=5

Config_borderPadding=2

in my config.ahk , but it doesn't show the rectangle border too.

**Comment by joten** [comment]
But it does not crash either?

**Comment by titepweb** [comment]
it looks like :



big gaps and no border @@

P/S I use windows 10 64bit , pro edition

I prefer small gaps between windows with approximate five-pixel border
outside focused window .

2016-02-11 2:52 GMT+07:00 joten <notifications@github.com>:

**Comment by joten** [comment]
I still could not produce a crash, but I could not get the border settings working on Windows 10 either. Therefor I deaktivated this feature for Winows 10.

@Chadehoc: Can you test again with the latest version, if a crash occurs?

**Comment by Chadehoc** [comment]
> @Chadehoc: Can you test again with the latest version, if a crash occurs?

Sorry for the delay.

I tried it and it didn't crash in about 30mn use, so I think it won't crash anymore.
