### ISSUE TITLE
Dual monitors not working (windows 10)

### ISSUE THREAD

**Issue by jamie-pate** [fuhsjr00/bug.n#70]
It seems like the dual monitor code is confused, It shows both 'monitor' collections on the same screen!
[DxDiag.txt](https://github.com/fuhsjr00/bug.n/files/102503/DxDiag.txt)

**Comment by jamie-pate** [comment]
Additionally the Config.ini creation key (#^s) doesn't seem to work, and AppData\Roaming\bug.n\Config.ini doesn't seem to have any effect.

Is there a way to turn on a debug log or dump from the console?

**Comment by joten** [comment]
What do you mean by "'monitor' collections"? How do the display settings of windows look like?

What do you mean by "doesn't seem to work"?
"On my machine it works." bug.n creates a file `Config.ini`, if it does not already exist, and writes the current state of monitors, views, layouts to it; if a file already exists the `Config_` lines are preserved.

**Comment by jamie-pate** [comment]
By 'monitor collections' I mean the windows tagged on each monitor. Both sets of tags seem to be placed on to of each other on the primary monitor.  My layout is something like [1][2]  where 1 is my primary display and 2 is extended.  My application base is also docked on the left instead of the bottom, (probably doesn't matter?)

**Comment by joten** [comment]
Can you make a screenshot of your display settings and post it here?

Can you give mor information on the issue regarding saving `Config.ini` by pressing <kbd>Win</kbd><kbd>Ctrl</kbd><kbd>S</kbd>?

**Comment by joten** [comment]
Any news on this one?

**Comment by jamie-pate** [comment]
No, sorry, I haven't had time to mess around with this. I don't have any idea why saving the config doesn't work. But really familiar with auto hotkey either.

**Comment by joten** [comment]
As far as I know this issue is not apparent for anyone else; with no more information to go on, I will close it. Please reopen it, if need arises.

**Comment by matthewbahr** [comment]
I definitely am having the same issue with the cfg not working. Pressing #^s just leaves me with a blank .tmp file. Hitting it again afterwards starts making more blank files with random kanji.

Using win10 build 14986

For what it's worth I have 3 monitors, 2 landscape 1 portrait. 

I just barely installed and was trying to get it working.

**Comment by millernb** [comment]
Including "Config_autoSaveSession=False" in my config file magically fixed my monitor issues (no bar on second screen, inability to send windows to second monitor, windows on second monitor vanishing when I changed workspaces on the first monitor).
