### ISSUE TITLE
the netmeter doesn't work

### ISSUE THREAD

**Issue by qijianjun** [fuhsjr00/bug.n#71]
I run bug.n with the version 0.9.

I have changed the default config item to this:
`Config_readinNetworkLoad=1`

but both the up and the down meter just show "0 B/s".

**Comment by joten** [comment]
From  bug.n/doc/Default_configuration.md:
`Config_readinNetworkLoad=0`
> If not false (`=0`) and given an identifying string for the network interface,
which should be monitored, the current network load (up and down) is read in
and displayed in the status bar.

E. g. the identifying string for my network interface, which is a "Qualcomm Atheros AR9002WB-1NG Wireless Network Adapter", is "AR9002WB".

**Comment by qijianjun** [comment]
Thanks, problem solved, I didn't get the point before when read the doc.
