### ISSUE TITLE
Acting as if CTRL button is pressed

### ISSUE THREAD

**Issue by SunnySanity** [fuhsjr00/bug.n#72]
When the ALT or WIN button is pressed in conjunction with one or more arrow keys, the keyboard acts as if the CTRL button is also pressed. I can most easily replicate this by holding down the ALT button, pressing up, down, up, down on the arrow keys, then releasing the ALT button. This only occurs when bug.n is running on my Windows 7 system. Tell me if you can replicate this.

Also, how do I avoid the "Would you like to reset the monitor configuration" popup message whenever I enter a fullscreen application (like a video game)?

**Comment by joten** [comment]
Strange, but I never encountered this behaviour and I could not reproduce it. How do you detect the error, i. e. what happens, if you reproduce the error? With bug.n running you may have `#^Down::View_setLayoutProperty(MY, 0, -1)`, which shows an effect when pressing <kbd>Win</kbd><kbd>Down</kbd> and by reproducing the error <kbd>Ctrl</kbd>; but how would you detect the error, if bug.n is not running?

> Also, how do I avoid the "Would you like to reset the monitor configuration" popup message

Currently not. But I will see to it, If I have time. I guess the monitor resolution is changed when you enter the video game in fulllscreen, therewith triggering the according function in bug.n. I will implement a configuration variable, with which you could disable the registration of the message when starting bug.n.

**Comment by SunnySanity** [comment]
When I release the button combination I used above, the ctrl button also registers as having been pressed. I first noticed this in a few video games, and then used a keyboard tester I found online to verify it. The ctrl key stops behaving weirdly when bug.n is not running, according to http://www.keyboardtester.com/.

I didn't know hotkeys affected button presses. I've attached my Config.ini as a .txt file since github doesn't support .ini attachments.
[configini.txt](https://github.com/fuhsjr00/bug.n/files/125833/configini.txt)

**Comment by joten** [comment]
Now that you come to mention it: Can you reproduce the error with the default configuration (no `Config.ini`)? &ndash; Your `Config.ini` has some peculiarities.

**Comment by SunnySanity** [comment]
I backed up the whole folder in Appdata/Roaming before deleting it to reset all my configurations, and I was still able to reproduce it. To make sure, I went on two of my friends' computers and downloaded the stable version of bug.n. I was able to reproduce it on both. Neither of them use any extra quality of life programs like bblean or autohotkey. Their systems are pretty close to stock, vanilla Windows 7.

So what I'm doing to test the issue is going to the site I linked above, holding down Alt, pressing Up Down Up Down on my arrow keys, releasing Alt, and seeing the Ctrl key lighting up as having been pressed. This only happens when bug.n is running on all the systems I tested. I also tried other keyboard input testers like http://lawrence.ecorp.net/inet/samples/keycodes.shtml

**Comment by srustamo** [comment]
Same here Win Server 2008.

**Comment by srustamo** [comment]
It seems to be related to a certain combination of modifiers pressed concurrently. I'm using stock config.

**Comment by srustamo** [comment]
I think what I have seen is a bit different, now that I researched it a bit.

What I experience is, on my system at least, that pressing <kbd>Win</kbd> first and <kbd>Shift</kbd> seems to trigger <kbd>Capslock</kbd> key, which seems to affect mouse select - I'm only able to select multiple items, and not unselect them. Pushing those keys in reverse restores the expected behavior.

**Comment by srustamo** [comment]
I also tried to see if the sequence affects other modifiers. In gVim (it shows the control chars) in pressing <kbd>Win</kbd> then <kbd>Ctrl</kbd> actually seems to make Ctrl sticky. After this pressing, say, <kbd>l</kbd> in gVim prints `^L`. The only way out of this state is reverse pressing the initial combo. 

I must say, I'm running this in RDP to Win Server 2008, using OSX RDC client.

**Comment by joten** [comment]
I tested again and could reproduce the issue.
<kbd>Ctrl</kbd> seems do get triggered after the modifier key (e. g. <kbd>Win</kbd>) has gone up, regardless of the key pressed with it, which is even not shown as been pressed; <kbd>Ctrl</kbd> is also triggerd with <kbd>Win</kbd><kbd>1</kbd>, <kbd>Win</kbd><kbd>BackSpace</kbd> and others.

Additionally, I tested with an AutoHotkey script, which only consisted of two lines and could reproduce the issue:
`!Up::Send {Volume_Up}`
`#Down::Send {Volume_Down}`

Therefor I think it is not a bug in bug.n; I even do not know if it is a bug at all. I never saw any side effects while using bug.n, did you -- beside noticing the effect, of course?

**Comment by SunnySanity** [comment]
I first noticed the effect when playing video games, since I often bind CTRL as a hotkey in games. The WIN key isn't too much of an issue, since I never press it in games, but it also happens with the ALT key, which I do use in games.

I couldn't reproduce the WIN 1 or WIN Backspace. It seems to happen for me mainly with WIN or ALT combined with Up or Down.
