### ISSUE TITLE
Colors have no effect

### ISSUE THREAD

**Issue by abienz** [fuhsjr00/bug.n#74]
I have added rules for Config_backColor_#1 and Config_fontColor_#1 to my Config.ini, but they don't appear to have any effect.

`
Config_backColor_#1=282828;282828;282828;282828;282828;282828;282828;282828;282828;
Config_fontColor_#1=fbf1c7;fbf1c7;fbf1c7;fbf1c7;fbf1c7;fbf1c7;fbf1c7;fbf1c7;
`

Also the documentation could do with an example to help clear up the syntax and colour type value to use.

**Comment by joten** [comment]
You will have to set all color variables: `Config_{back,fore,font}Color_#{1,2,3}`; if any of these is not set, bug.n will not be satisfied and overwrite all with the default values retrieved from the system settings.

**Comment by joten** [comment]
I reverted back to the commit right after the release of version 9.0.0-beta.1 and inspected the code more closely; with the latest release and the current development version each color variable is set individually. Therefor, if you previously used the development version, use one of the versions mentioned above.
