### ISSUE TITLE
Config.ini not saving

### ISSUE THREAD

**Issue by janus0** [fuhsjr00/bug.n#75]
Pressing windows key+ctrl+s isn't saving the config.ini file. Instead, if I hold this key combo for a few seconds, a .tmp file and a file titled 쁘Ϡ㯸 are created in the bug.n.exe directory. Pressing windows key+ctrl+E works as expected, but isn't able to find a config.ini file since obviously I can't create one. Thoughts?

[쁘Ϡ㯸.txt](https://github.com/fuhsjr00/bug.n/files/151628/default.txt)

**Comment by joten** [comment]
Well, I cannot reproduce the problem.

The content of the file looks okay. The easiest way around this problem would be to copy the file `usr\default_01.ini` from the bug.n directory to `Config.ini` in the bug.n data directory, in the hope the file is not scrambled up again by anything.

**Comment by janus0** [comment]
Thanks joten, I actually went ahead and just started using the AHK script instead of the exe.
