### ISSUE TITLE
Compiled binary size

### ISSUE THREAD

**Issue by ipstone** [fuhsjr00/bug.n#77]
Hello, 

when I compiled bug.n (src/Main.ahk) on windows 7, x64, with Ahk2Exe, somehow my binary size is around 900kb, whereas the stable downloaded version only is about 300kb.

Though it's just a small difference of size, I would like to know how the stable/downloaded version was compiled to generate a smaller binary?

Thanks!

**Comment by ipstone** [comment]
I actually found compiling the master branch, the final binary is about 900kb in size. 
- So probably the stable download version refers to an 'earlier' version of bug.n. 

In any case, I am using the mater branch now, so I am closing this issue.

**Comment by joten** [comment]
The difference lies in the use of mpress.

I re-installed AutoHotkey lately and forgot to install mpress, therefor the latest binary is uncompressed; with compression it result in a binary size of 334 KB.

Sadly the site linked at https://autohotkey.com/docs/Scripts.htm#ahk2exe, http://www.matcode.com/mpress.htm, is currently unavailable.
