### ISSUE TITLE
Suggestion to phase the View_shuffleWindow(1) function out

### ISSUE THREAD

**Issue by janus0** [fuhsjr00/bug.n#78]
Maybe I'm missing something, but it seems to make more sense to shift every window up by a position rather than just the active window shifting positions-- it will achieve the same effect whilst saving the hassle of needing to find and click the window you want to move.

Example: I have 1 large window on the left half of my screen, and 3 smaller stacked windows on the right side. I'm done reading the big window, and I now want to switch a smaller window over to where the bigger window was so that I can navigate it easier whilst still keeping my other small windows in my peripheral (hence not simply maximizing the window I want to switch to). I can press a hotkey 2-3 times, and it will now be in the left half of my screen (whereas with the way things are now, I'd have to move my eyes across the screen, move my mouse, click the window to activate it, and THEN press the hotkey 2-3 times to shift it).

Thoughts?

**Comment by joten** [comment]
The purpose of the `View_shuffleWindow` function was to change the order of windows in the layout.

In your case the easier way for

> have to move my eyes across the screen, move my mouse, click the window to activate...

would be to press the hotkey `#Down::View_activateWindow(0, +1)` or `#Up::View_activateWindow(0, -1)` 2-3 times and than to use the hotkey `#+Enter::View_shuffleWindow(1)`, which puts the active window to the master area.
