### ISSUE TITLE
Bug.n switches to desktop with steam whenever message is received

### ISSUE THREAD

**Issue by janus0** [fuhsjr00/bug.n#81]
Is there a way to disable this behavior?

**Comment by joten** [comment]
Adding the line `Config_onActiveHiddenWnds=hide` or `Config_onActiveHiddenWnds=tag` to your `Config.ini` would solve the issue; you may also tag the steam window so that it will be visible on all views. -- I do not use steam, but it seems to behave like a instant messaging window.
