### ISSUE TITLE
Two afx windows behave differently, one cann't be managed

### ISSUE THREAD

**Issue by qijianjun** [fuhsjr00/bug.n#82]
I have two windows with both have the Afx class, one is Mp3tag, which has a maximize flag and cant't be managed, the other is MarkdownEditor, which perform well. It seems to be Mp3tag's problem?

The Mp3tag window is like [this](http://postimg.org/image/sewe0pkbr/).

bug.n version: 0.9.0

>ID: 0x191210
class:	Afx:00400000:b:00010003:00000006:0C0412C9
title:	Mp3tag v2.75  -  F:\audiobooks\tmp\
process:	Mp3tag.exe [5840]
style:	0x150F0000
metrics:	x: -8, y: 32, width: 1616, height: 876
tags:	128
Config_rule=Afx:00400000:b:00010003:00000006:0C0412C9;Mp3tag v2.75  -  F:\audiobooks\tmp\;;1;1;128;0;0;0;maximize

>ID: 0x551246
class:	Afx:00F60000:b:00010003:00000006:001D11A9
title:	Untitled - MarkdownEditor
process:	MarkdownEditor.exe [3076]
style:	0x140FC000
metrics:	x: 720, y: 40, width: 880, height: 860
tags:	128
Config_rule=Afx:00F60000:b:00010003:00000006:001D11A9;Untitled - MarkdownEditor;;1;1;128;0;0;0;

**Comment by joten** [comment]
* Can the window of Mp3tag be managed, if it is not maximizied?
* Was Mp3tag started as Administrator?
* Can you add the following line in your `Config.ini` and press the hotkey <kbd>Win</kbd><kbd>Ctrl</kbd><kbd></kbd>, when the Mp3tag window is active?

`Config_hotkey=#^o::Manager_override(1;0;0;0;0;0;)`

Does it have any effect?

**Comment by qijianjun** [comment]
1. When mp3tag last exited before runing bugn, it was maximum, so once runing bugn, the mp3tag window is always maximum and can't be resized. I exit bugn and resize mp3tag window to a normal size, then run bugn again, this time it's not maximum, but still can't be resized.
2. It was not started as Administrator.
3. It seems my bugn don't have the `Manager_override` function, i add the line to config.ini, but with `win+ctrl+o`, there is no effect on any window.

Here the `win+i` info, the metrics data never change:

>ID: 0x1b1103c
class:	Afx:00400000:b:00010003:00000006:149113F1
title:	Mp3tag v2.75  -  F:\家常读书\
process:	Mp3tag.exe [11756]
style:	0x140F0000
metrics:	x: 76, y: 86, width: 664, height: 474
tags:	128
Config_rule=Afx:00400000:b:00010003:00000006:149113F1;Mp3tag v2.75  -  F:\家常读书\;;1;1;128;0;0;0;

**Comment by joten** [comment]
Although, I am a bit late on this one...

The rule, which was created as an example with <kbd>Win</kbd><kbd>I</kbd>, indicates, that the window is in fact managed; the fourth field is set to 1 and tags are assigned. The conclusion would be, that it just cannot be resized.

Though, I cannot identifiy the difference in style `0x0000C000`, I do not have a clue on this one. I would mark Mp3tag as incompatible regarding bug.n and close theis issue.

**Comment by joten** [comment]
Please reopen this issue, if it is still relevant.
