### ISSUE TITLE
goldendict(QWidget) cann't be resize to smaller than half the screen when be main window

### ISSUE THREAD

**Issue by qijianjun** [fuhsjr00/bug.n#84]
Some window, chrome for example, will stop resizing to smaller when it's already very narrow, I guess the reason is it has so many tabs and it can't show them if get narrower.

But if the GoldenDict window is the main window in the tag, it will refuse resize to be narrower if its width is halt the screen. If its not the main window, it can be very narrow even can't be seen.

bug.n version: 0.9.0

>ID: 0x20708
class:	QWidget
title:	hello - GoldenDict
process:	GoldenDict.exe [4560]
style:	0x970F0000
metrics:	x: 0, y: 40, width: 771, height: 860
tags:	4
Config_rule=QWidget;hello - GoldenDict;;1;1;4;0;0;0;maximize

**Comment by joten** [comment]
There are applications, which set a minimal size for their windows; Explorer e. g. has a minimal width of 161 and height of 243 pixel.

Is the window information above from the window not being the main window? If so, is the window perhaps not narrower but just moved out of site? -- Moving it by mouse would show the remaining part, without bug.n interfering.

**Comment by qijianjun** [comment]
@joten I test it and you are right.

Without bug.n, goldendict window can't be resized to narrower than halt of the screen.
With bug.n, when goldendict is not the main window and the other window get very wide, it will move out of the screen, not get narrower than halt of the screen.
