### ISSUE TITLE
Not sure what this invisible window in desktop 1 and 5 is?

### ISSUE THREAD

**Issue by janus0** [fuhsjr00/bug.n#85]
I was adding some config rules for my steam windows, and when testing, discovered there's an invisible window on desktop 1 and 5. I can focus it via the activate window command, but I can't close it -- removing the config rules, implementing a fresh config file, and restarting windows did nothing. It wasn't there until I added the steam config rules. Here's the window info and my config file:

ID: 0x10106
class:	Progman
title:	Program Manager
process:	Explorer.EXE
style:	0x96000000
metrics:	x: 0, y: 0, width: 1680, height: 1050
tags:	

[Config.txt](https://github.com/fuhsjr00/bug.n/files/164603/Config.txt)

**Comment by joten** [comment]
I guess you are using Windows 7 -- than that window is the desktop. A restart of Windows and reverting the the configuration should have resolved the issue.

Nevertheless I have reverted the commits from "initial src commit of v10" onwards. Please test, if the issue still occurs.
