### ISSUE TITLE
remapping toggle floating windows key isn't responding to the new keybinding

### ISSUE THREAD

**Issue by ipstone** [fuhsjr00/bug.n#86]
Hello,

I tried the following remap, somehow it's not working properly:

```
Config_hotkey=#+d::
Config_hotkey=!+d::Window_toggleDecor()
Config_hotkey=#+f::
Config_hotkey=!+f::View_toggleFloatingWindow()
```

I am trying to use !+f,  to toggleFloatingWindow. However, the new keybinding simply won't get a response, not sure where the error is from.

**Comment by joten** [comment]
Unfortunately, I cannot reproduce the problem. I tested with the current development version 0780f25c18ac2ce7e0fe74c14f263c3cc9b66ae4 and a fresh `Config.ini` with just the given lines above added.

Do other configuration settings work, therewith confirming the use of the edited `Config.ini`?

**Comment by joten** [comment]
Any news on this one?

**Comment by ipstone** [comment]
Hi Joten,

Thank you for reaching out. Unfortunately I haven't used bug.n for several
weeks to test this out, as switching to a new workstation with much larger
screen area. Please close this one, if in the future I find the bug again,
I will open a new ticket.

Thanks

**Comment by wired** [comment]
I'm having the same issue with these two:

```
Config_hotkey=#t::Window_toggleDecor()
Config_hotkey=#v::View_toggleFloatingWindow()
```

The log says they're registered, but trying to invoke them doesn't work.

```
2016-10-19 16:19:52 Processing configured hotkey: Config_hotkey=#t::Window_toggleDecor()
2016-10-19 16:19:52   Hotkey: #t -> Window_toggleDecor()
2016-10-19 16:19:52 Processing configured hotkey: Config_hotkey=#v::View_toggleFloatingWindow()
2016-10-19 16:19:52   Hotkey: #v -> View_toggleFloatingWindow()
```

Other bindings work well.
The original bindings work, but I want to use those keys for something else.

**Comment by wired** [comment]
Turns out 8.4.0 is really old, problem is solved in master.
