### ISSUE TITLE
Why some windows have black strips in the title panel?

### ISSUE THREAD

**Issue by qijianjun** [fuhsjr00/bug.n#87]
Some window always have the black strips, eg:

![ConEmu64](https://cloud.githubusercontent.com/assets/612912/13720369/bd795da0-e841-11e5-98f3-243ad8928acb.png)

Some sometimes have, sometimes not, eg:

![sumatraPdf](https://cloud.githubusercontent.com/assets/612912/13720376/f3444602-e841-11e5-8c78-478d4da7b83a.png)

**Comment by joten** [comment]
I have not the foggiest notion. The first looks like the window title is not drawn, the second seems to have the height of the bug.n bar.

Does anything change, if your resize the window or change the view therewith redrawing the window?
