### ISSUE TITLE
windows not managed (or wrongly) when starting in a 'Floating' desktop

### ISSUE THREAD

**Issue by ipstone** [fuhsjr00/bug.n#89]
I am using the current head version of bug.n and found : 

In a dual monitor setting, if the first view on the first monitor is set as 'float', i.e.: ><>  , then newly launched app is no longer managed by bug.n.

This is probably a bug - even if the view is set as float mode, I think the newly launched app should still be managed?

Thanks

**Comment by joten** [comment]
I tested the current development version and could not reproduce the issue. I even set the floating layout on all views on all monitors, but windows were always managed (<kbd>Win</kbd><kbd>i</kbd>) -- they just were not tiled.

With the layout on the active view of the second monitor not set to floating and opening a window there, it is managed and tiled as expected.
