### ISSUE TITLE
BUG - fix: Manager.ahk

### ISSUE THREAD

**Issue by ipstone** [fuhsjr00/bug.n#90]
I encountered a bug in **_Manager.ahk,_** that **_WIN_VISTA_** should be quoted similarly as in Config.ahk.
If it's not quoted, autohotkey considers it as a global variable and gives warnings. After I added quotes, the warning disappeared. 

Thanks

6 matches for "vista" in buffer: Manager.ahk
    736:  If (Config_borderWidth > 0) Or (Config_borderPadding >= 0 And A_OSVersion = WIN_VISTA)
    738:    ncmSize := VarSetCapacity(ncm, 4 * (A_OSVersion = WIN_VISTA ? 11 : 10) + 5 * (28 + 32 * (A_IsUnicode ? 2 : 1)), 0)
    743:    If (Config_borderPadding >= 0 And A_OSVersion = WIN_VISTA)
   1003:  If (Config_borderWidth > 0) Or (Config_borderPadding >= 0 And A_OSVersion = WIN_VISTA)
   1005:    ncmSize := VarSetCapacity(ncm, 4 * (A_OSVersion = WIN_VISTA ? 11 : 10) + 5 * (28 + 32 * (A_IsUnicode ? 2 : 1)), 0)
   1012:    If (Config_borderPadding >= 0 And A_OSVersion = WIN_VISTA)

In Config.ahk, it's quoted:
2 matches for "vista" in buffer: Config.ahk
    165:    ncmSize := VarSetCapacity(ncm, 4 * (A_OSVersion = "WIN_VISTA" ? 11 : 10) + 5 * (28 + 32 * (A_IsUnicode ? 2 : 1)), 0)
    176:    ncmSize := VarSetCapacity(ncm, 4 * (A_OSVersion = "WIN_VISTA" ? 11 : 10) + 5 * (28 + 32 * (A_IsUnicode ? 2 : 1)), 0)

**Comment by joten** [comment]
Thanks for pointing this out.
