### ISSUE TITLE
Monitor_activateView(>) is not working

### ISSUE THREAD

**Issue by ipstone** [fuhsjr00/bug.n#91]
```
Config_hotkey=!Left::Monitor_activateView(>)
Config_hotkey=!Right::Monitor_activateView(<)

```
is currently listed in the default_hotkeys.md, however, it's not working.

I tested  Config_hotkey=!Left::Monitor_activateView(-1), which is working.

Additionally, is there a way to move to the next neighboring view (on the left, on the right etc)?

Thanks

**Comment by joten** [comment]
With the current head at the time -- by the way sorry for the late response -- I found the following in the doc:
> `Config_hotkey=#BackSpace::Monitor_activateView(-1)`
> Activate the previously activated view. 
>
> You may also use `Monitor_activateView(0, -1)` or `Monitor_activateView(0, +1)` for activating the previous or next adjacent view.

`Config_hotkey=!Left::Monitor_activateView(>)` is obsolete.

`Config_hotkey=!Left::Monitor_activateView(0, -1)` and 
`Config_hotkey=!Right::Monitor_activateView(0, +1)` should be right.

I hope, I did not miss anything.
