### ISSUE TITLE
Taskbar icon issue in compiled version

### ISSUE THREAD

**Issue by x29a** [fuhsjr00/bug.n#94]
I noticed quite some time ago, that when running the compiled version, its icon in the taskbar would either be empty (so gray space) or it would steal some other applications icon (e.g. "new mail") which is quite confusing.

I then looked at the code and found [this condition](https://github.com/fuhsjr00/bug.n/blob/7b92900432345f074b6817e1fc0af0254b59da7d/src/Main.ahk#L44) so i manually placed the logo.ico in the folder where the .exe resides and TATAAA, the right icon is applied.

Running on Windows 7 64bit, two monitors, classic theme, i usually start Bug.N with a link to the following batchfile in the "startup" folder:

`start E:\bin\bugn\20160409_bugn.exe E:\bin\bugn`

Did something in the compilation process change? Maybe we can add the resources to the compiled output like suggested [here](https://autohotkey.com/board/topic/37699-tutorial-how-to-compile-ahk-files-include-your-own-icons/).

The .exe file itself shows the correct icon when displayed in the file explorer.

**Comment by joten** [comment]
Although I could not reproduce the issue, I applied the fix as suggested. -- Thanks by the way for the suggestion.

Can you test the current development version and see, if the bug as you have observed it has been fixed?

**Comment by x29a** [comment]
Unfortunately, the icon is still random:
![bugn_icon](https://cloud.githubusercontent.com/assets/204177/14522980/8f0bed84-0231-11e6-92d0-c84c0fc38320.png)

Since im not familiar with AHK and there is the workaround to place the icon in the same folder, feel free to close this as WONTFIX.

Its just weird that this seems to be a regression from old versions and you cant reproduce it. Oh well.

**Comment by x29a** [comment]
The PR 97 fixes the problem for me

**Comment by joten** [comment]
Thanks again for the provided fix.
