### ISSUE TITLE
Warnings on unassigned values

### ISSUE THREAD

**Issue by x29a** [fuhsjr00/bug.n#95]
Starting with the Bug.N version (bugn.exe) from Apr 9, 2016 (and also the one from yesterday), i get the following warning on startup:

> Warning: This variable has not been assigned a value.
> 
> Specifically: newIdleTime (a static variable)
> 
> Line#
> ---> 2466: [oldIdleTime := newIdleTime](https://github.com/fuhsjr00/bug.n/blob/master/src/ResourceMonitor.ahk#L122)
> 
> For mor details, read the documentation for #Warn

The same appears for 

> 2467: [oldKrnlTime := newKrnlTime](https://github.com/fuhsjr00/bug.n/blob/master/src/ResourceMonitor.ahk#L123)

and

> 2468: [oldUserTime := newUserTime](https://github.com/fuhsjr00/bug.n/blob/master/src/ResourceMonitor.ahk#L124)

This also happens with a completely empty "data" folder, so i assume it is configuration independant.

After clicking the warnings away, Bug.N works like a charm.

**Comment by joten** [comment]
I hope, I got them all now.

**Comment by x29a** [comment]
Warnings are gone with [bugn.exe from 20160413](https://github.com/fuhsjr00/bug.n/commit/cc9381b245e4953f139c47199980a1212473a3af#diff-94220df59411637afd530c3bb732687b). Thanks!

**Comment by x29a** [comment]
Got another warning:

> 
> Specifically: View_#1_#1_margin (a global variable)
> Line #
> [2969: StringSplit,View_#%n%_#%w%_margin,View_#%n%_#%w%_margin,;](https://github.com/fuhsjr00/bug.n/blob/master/src/View.ahk#L227)

**Comment by webframp** [comment]
Saw the same issue, warning on unassigned vars today. Using bugn.exe from commit cc9381b245e4953f139c47199980a1212473a3af

This popped up when I would normally get the message about 'would you like to reset the windows'

![image](https://cloud.githubusercontent.com/assets/774378/14792127/e4803758-0ae6-11e6-95ce-33e05b8b9f79.png)

**Comment by jfmcbrayer** [comment]
I am getting these as well, bugn.exe from cc9381b245e4953f139c47199980a1212473a3af.

After getting the message about "Would you like to reset the window configuration":

Warning: This variable has not been assigned a value.

Specifically: Monitor_#2_aView_#1 (a global variable)

        Line #
--->    2009: v:= Monitor_#%A_Index%_aView_#1

For more details, read the documentation for #Warn.



Warning: This variable has not been assigned a value.

Specifically: View_#2_#_wndIds (a global variable)

        Line#
--->    2010: shownWndIds .= View_#%A_Index%_#%v%_wndIds

For more details, read the documentation for #Warn.

**Comment by joten** [comment]
Please test with 744ee1f7d709c263667673e0a1e92d155c539547, when convenient.

**Comment by webframp** [comment]
Fixes the warning popup for me :+1:

**Comment by Chadehoc** [comment]
Another warning (happened on rev c5412d5 hiding a window by `#^m`)

![capture](https://cloud.githubusercontent.com/assets/1562517/15358244/ac6f1eae-1d03-11e6-8c8e-75bb52e3c338.PNG)

(I had the choice between #101, #102, and this one to report, I chose the oldest)

**Comment by jfmcbrayer** [comment]
I'm getting this one on c5412d5394674663454dcb18fd578f7ad57e405c, when plugging in a second monitor, before getting the dialog asking to change the window configuration. There are a few more that follow.

Warning: This variable has not been assigned a value.

Specifically: Monitor_#2_aView_#1 (a global variable)

           Line#
--->       2019: v := Monitor_#%A_Index%aView_#1

For more details, read the documentation for #Warn

**Comment by huffstler** [comment]
![bugn_error](https://cloud.githubusercontent.com/assets/9092204/15895465/7b0bb3ca-2d59-11e6-8c01-7f79a8e44b36.png)

I am also getting warnings on c5412d5. I have found that a lot of the time the warnings (for me at least) happen when I try to move focus from one window to another when a program hasn't fully started yet.

For example; when starting outlook and the splash screen appears, if I use the Windows+(Up/Down) key nothing happens until Outlook loads fully.After outlook fully loads trying to navigate using the keys again will throw the warning for me. I'll update with more information later. at work currently.

**Comment by joten** [comment]
Further warnings are circumvented.

It may be possible those issues cannot easily be fixed with `_isFloating` set to `False = 0 = ""` being garbage collected and therewith not assigned a value afterwards.
