### ISSUE TITLE
Config_hotkey #j::View_activateWindow(0,+1) doesn't create mapping...?

### ISSUE THREAD

**Issue by kashperanto** [fuhsjr00/bug.n#96]
I am having a very odd issue in that my bug.n can't seem to make this very simple binding.  The odd part is that #+j works perfectly fine to shuffle the windows, but I can't get this to work for the life of me:

Config_hotkey=#Down::
Config_hotkey=#j::View_activateWindow(0, +1)
Config_hotkey=#Up::
Config_hotkey=#k::View_activateWindow(0, -1)
Config_hotkey=#+Down::
Config_hotkey=#+j::View_shuffleWindow(0, +1)
Config_hotkey=#+Up::
Config_hotkey=#+k::View_shuffleWindow(0, -1)

Earlier I tried to use a modified default Config.ini and had to restart my computer because the layout lost its mind (the top bar was being managed as though it were a window...?), and even after disabling bug.n the desktop layout was messed up.  It seems I can only use a simple remapping like above, but it seems very arbitrary to me that the #j and #k bindings fail while the #+j and #+k bindings work flawlessly.

I'm running this on a Lenovo Thinkpad T450 with Windows 7, so nothing too unusual as far as I'm concerned.  I'm going to give it one more restart to see if the bindings take hold.

Another related issue is that the #^s command does not create a Config.ini file as it says in the instructions.  I had to manually create that file, and this was also the case on my previous Win7 system as well (although the bindings worked on that one).

**Comment by kashperanto** [comment]
Hah, figures I would find the issue once I post it here ;P

I believe the problem is that the default Config.ini is using some different interface for those functions.  I dug through the AHK source and you used View_activateWindow(+1) without the first argument, so I changed it to that and now everything seems to be working.  You should probably change the default file if those functions are not what is currently used, unless my original use was correct and was just not functioning for whatever reason.

Thanks

**Comment by joten** [comment]
Unfortunately, I could not reproduce the problem. I copied the lines above to my test-`Config.ini` and it worked as expected with the current development version of bug.n.

**usr\default_01.ini** currently has the following lines:
````
;Config_hotkey=#Down::View_activateWindow(0, +1)
;Config_hotkey=#Up::View_activateWindow(0, -1)
;Config_hotkey=#+Down::View_shuffleWindow(0, +1)
;Config_hotkey=#+Up::View_shuffleWindow(0, -1)
````

**Config.ahk**:
````
#Down::View_activateWindow(0, +1)
#Up::View_activateWindow(0, -1)
#+Down::View_shuffleWindow(0, +1)
#+Up::View_shuffleWindow(0, -1)
````

And from **View.ahk**:
`View_activateWindow(i, d = 0) {`

Which version are you using?

I also could not reproduce the issue regarding saving the `Config.ini`. Did the file `%APPDATA%\bug.n\Config.ini` did not exist at all or did it just not have the expected content?

**Comment by kashperanto** [comment]
Hi, thanks for taking a look at this.  I'm running bug.n-8.4.0, installed from the bug.n-8.4.0.zip file.  It looks like my zip file doesn't have the same files as the master zip file (I don't recall how I ended up downloading this one).  I _do_ remember having to copy the Config.ini file from this site because my zip file doesn't have a usr/ folder.  I suppose if you are looking for that default ini file it would explain why my bug.n doesn't create a Config.ini when I do the #^s command.

I will see if I can recreate the issue after reinstalling bug.n from the master zip file.

Thanks for the help

**Comment by joten** [comment]
Please reopen the issue, if there still is a problem.
